"""Chapter 1 — What is meteorology?"""
import sys
sys.path.insert(0, 'tools/content')
from build import T, P, L, N, write_chapter

chapter = {"id": "ch01", "num": 1, "stage": 1,
 "title": T("气象学是什么", "What is meteorology?", "Apakah meteorologi?"),
 "sources": ["PAM", "ESS", "WMO-75", "MET-HOME", "ECMWF-WHO", "NOAA-EMC-GEFS", "JMA-MSC", "ASMC"],
 "sections": [
 {"id": "s1", "heading": T("研究天空的科学", "The science of the sky", "Sains tentang langit"), "level": "basic", "blocks": [
  P("{{t:meteorology}}是研究地球大气的科学：大气里发生的物理、化学和运动过程，以及大气和底下的陆地、海洋怎样互相影响。这些过程合起来，就产生了我们每天经历的天气。",
    "{{t:meteorology}} is the science of the Earth's atmosphere: the physical, chemical and moving processes in the air, and how the air interacts with the land and sea beneath it. Together these processes make the weather we live with every day.",
    "{{t:meteorology}} ialah sains tentang atmosfera Bumi: proses fizikal, kimia dan pergerakan dalam udara, serta bagaimana udara berinteraksi dengan daratan dan lautan di bawahnya. Bersama-sama, proses ini menghasilkan cuaca yang kita alami setiap hari.",
    defines=["meteorology"], src=["PAM:1"]),
  P("地球可以分成四个“圈”：水圈（海洋、河流）、岩石圈（陆地）、大气圈（包围地球的空气）和生物圈（所有生物）。气象学研究的是大气圈，但它离不开另外三个圈：海洋供应水汽，陆地被太阳晒热，植物和动物又受天气影响。",
    "The Earth can be divided into four 'spheres': the hydrosphere (oceans and rivers), the lithosphere (solid land), the atmosphere (the air around the planet) and the biosphere (everything alive). Meteorology studies the atmosphere, but it cannot ignore the other three: the sea supplies water vapour, the land is heated by the Sun, and plants and animals are shaped by the weather.",
    "Bumi boleh dibahagikan kepada empat ‘sfera’: hidrosfera (lautan dan sungai), litosfera (daratan), atmosfera (udara yang menyelubungi planet) dan biosfera (semua benda hidup). Meteorologi mengkaji atmosfera, tetapi tidak boleh mengabaikan tiga yang lain: laut membekalkan wap air, daratan dipanaskan oleh Matahari, dan tumbuhan serta haiwan dipengaruhi cuaca.",
    src=["PAM:1"]),
  N("myth", "“气象学”的英文 meteorology 跟流星（meteor）没有关系。它来自希腊文 meteorologia，意思是“研究天上的东西”。古希腊人把天空中出现的一切——云、雨、闪电——都叫做 meteora。",
    "Meteorology has nothing to do with meteors. The word comes from the Greek meteorologia, ‘the study of things up above’. The ancient Greeks called everything seen in the sky — clouds, rain, lightning — meteora.",
    "Meteorologi tiada kaitan dengan meteor. Perkataan itu berasal daripada bahasa Yunani meteorologia, ‘kajian tentang benda di atas’. Orang Yunani purba memanggil segala yang dilihat di langit — awan, hujan, kilat — meteora.",
    src=["PAM:1"]),
 ]},
 {"id": "s2", "heading": T("天气与气候", "Weather and climate", "Cuaca dan iklim"), "level": "basic", "blocks": [
  P("{{t:weather}}是某个地方、某个时间的大气状况：现在热不热、有没有下雨、风大不大。天气每天、甚至每个小时都在变。",
    "{{t:weather}} is the state of the atmosphere at a particular place and time: how hot it is right now, whether it is raining, how strong the wind is. Weather changes from day to day and even hour to hour.",
    "{{t:weather}} ialah keadaan atmosfera di sesuatu tempat pada sesuatu masa: betapa panasnya sekarang, sama ada hujan, betapa kuat angin. Cuaca berubah dari hari ke hari, malah dari jam ke jam.",
    defines=["weather"], src=["ESS:15"]),
  P("描述天气用的是几样可以量的东西，叫做{{t:weather-elements}}：",
    "Weather is described by a handful of things that can be measured, the {{t:weather-elements}}:",
    "Cuaca diterangkan oleh beberapa perkara yang boleh diukur, iaitu {{t:weather-elements}}:",
    defines=["weather-elements"], src=["ESS:15"]),
  L(("气温：空气有多热或多冷", "Air temperature: how hot or cold the air is", "Suhu udara: betapa panas atau sejuk udara"),
    ("气压：头顶上空气的重量压下来的力", "Air pressure: the force of the air above pressing down", "Tekanan udara: daya udara di atas yang menekan ke bawah"),
    ("湿度：空气里有多少水汽", "Humidity: how much water vapour the air holds", "Kelembapan: berapa banyak wap air dalam udara"),
    ("云：天上看得见的小水滴或冰晶", "Clouds: visible masses of tiny water droplets or ice crystals", "Awan: kumpulan titisan air atau hablur ais halus yang kelihatan"),
    ("降水：雨、毛毛雨、冰雹等从天上落下的水", "Precipitation: rain, drizzle, hail and other water falling from the sky", "Kerpasan: hujan, gerimis, hujan batu dan air lain yang turun dari langit"),
    ("能见度：能看多远", "Visibility: how far you can see", "Keterlihatan: sejauh mana anda boleh melihat"),
    ("风：空气的流动，有速度也有方向", "Wind: moving air, with both a speed and a direction", "Angin: udara yang bergerak, dengan kelajuan dan arah"),
    src=["ESS:15"]),
  P("{{t:climate}}则是一个地方长期的天气：通常拿 30 年的平均值和极端值来描述。天气告诉你“今天要不要带伞”，气候告诉你“这里一年里哪几个月雨最多”。",
    "{{t:climate}} is the weather of a place over the long run, usually described by averages and extremes over 30 years. Weather tells you whether to take an umbrella today; climate tells you which months of the year are wettest here.",
    "{{t:climate}} pula ialah cuaca sesuatu tempat dalam jangka panjang, biasanya diterangkan dengan purata dan nilai ekstrem selama 30 tahun. Cuaca memberitahu sama ada perlu membawa payung hari ini; iklim memberitahu bulan mana paling basah di sini.",
    defines=["climate"], src=["ESS:15-16"]),
 ]},
 {"id": "s3", "heading": T("为什么要学气象", "Why meteorology matters", "Mengapa meteorologi penting"), "level": "basic", "blocks": [
  P("天气影响几乎每一个行业。预先知道坏天气，就能减少生命和财产的损失：",
    "Weather affects almost every kind of work. Knowing about bad weather in advance saves lives and property:",
    "Cuaca mempengaruhi hampir setiap jenis pekerjaan. Mengetahui cuaca buruk lebih awal menyelamatkan nyawa dan harta benda:",
    src=["PAM:2-3"]),
  {"type": "keyval", "src": ["PAM:2-3"], "rows": [
   {"k": T("农业", "Farming", "Pertanian"), "v": T("作物的生长、发育和产量都取决于雨量、阳光和温度", "Crop growth, development and yield depend on rainfall, sunshine and temperature", "Pertumbuhan, perkembangan dan hasil tanaman bergantung pada hujan, cahaya matahari dan suhu")},
   {"k": T("畜牧", "Livestock", "Ternakan"), "v": T("肉、蛋、奶的产量都受天气影响", "Meat, egg and milk production all respond to the weather", "Pengeluaran daging, telur dan susu semuanya dipengaruhi cuaca")},
   {"k": T("航空", "Aviation", "Penerbangan"), "v": T("飞行员需要知道云、风和雷暴", "Pilots need to know about cloud, wind and thunderstorms", "Juruterbang perlu tahu tentang awan, angin dan ribut petir")},
   {"k": T("航海与渔业", "Shipping and fishing", "Perkapalan dan perikanan"), "v": T("大浪、强风和风暴关系到海上安全", "High waves, strong winds and storms decide safety at sea", "Ombak besar, angin kuat dan ribut menentukan keselamatan di laut")},
   {"k": T("水资源", "Water", "Sumber air"), "v": T("规划灌溉和用水，要知道什么时候、哪里、需要多少水", "Planning irrigation and supply means knowing when, where and how much water is needed", "Merancang pengairan dan bekalan air memerlukan pengetahuan bila, di mana dan berapa banyak air diperlukan")},
   {"k": T("防灾", "Disasters", "Bencana"), "v": T("事先预警风暴、水灾和干旱，可以减少伤亡", "Early warning of storms, floods and drought reduces loss of life", "Amaran awal ribut, banjir dan kemarau mengurangkan kehilangan nyawa")},
   {"k": T("健康", "Health", "Kesihatan"), "v": T("有些疾病的传播和天气有关", "The spread of some diseases is linked to the weather", "Penyebaran sesetengah penyakit berkait dengan cuaca")}]},
 ]},
 {"id": "s4", "heading": T("农业气象学", "Agricultural meteorology", "Meteorologi pertanian"), "level": "basic", "blocks": [
  P("{{t:agrometeorology}}研究天气、气候和水文条件跟农业生产的关系：天气怎样影响作物和牲畜，又怎样利用这些知识来提高产量、减少损失。它关心的范围，从作物根部伸到的土壤深处，一直到植物生长的高度。",
    "{{t:agrometeorology}} studies how weather, climate and water conditions relate to farming: how the weather affects crops and livestock, and how that knowledge can raise yields and cut losses. Its field reaches from the soil as deep as roots go, up to the height at which plants grow.",
    "{{t:agrometeorology}} mengkaji hubungan cuaca, iklim dan keadaan air dengan pertanian: bagaimana cuaca mempengaruhi tanaman dan ternakan, dan bagaimana pengetahuan itu boleh meningkatkan hasil serta mengurangkan kerugian. Bidangnya merangkumi tanah sedalam akar hingga ketinggian tumbuhan hidup.",
    defines=["agrometeorology"], src=["PAM:32-33"]),
  P("农业气象知识可以帮助农民：",
    "Agricultural meteorology helps farmers to:",
    "Meteorologi pertanian membantu petani untuk:",
    src=["PAM:33"]),
  L(("选择播种和种植的时间", "Choose when to sow and plant", "Memilih masa menyemai dan menanam"),
    ("决定什么时候除草、施肥、喷药，减少肥料和农药被雨冲走", "Time weeding, fertilising and spraying, so less is washed away by rain", "Menentukan masa merumput, membaja dan menyembur, supaya kurang dihanyutkan hujan"),
    ("决定什么时候收成", "Decide when to harvest", "Menentukan masa menuai"),
    ("改善作物周围的小环境", "Improve the conditions immediately around the crop", "Memperbaik keadaan di sekeliling tanaman"),
    ("了解天气和病虫害的关系", "Understand how weather drives disease and pests", "Memahami bagaimana cuaca mendorong penyakit dan perosak"),
    ("了解气候变化对农业的影响", "Understand what climate change means for farming", "Memahami kesan perubahan iklim terhadap pertanian"),
    src=["PAM:33"]),
  P("所以农艺、园艺、土壤学、植物病理学、昆虫学和农业工程，全都需要气象资料。第 9 阶段会再回到农业，那时你已经懂得足够的气象学，可以看懂这些应用。",
    "That is why agronomy, horticulture, soil science, plant pathology, entomology and agricultural engineering all need weather information. Stage 9 returns to farming, when you will know enough meteorology to follow the applications.",
    "Itulah sebabnya agronomi, hortikultur, sains tanah, patologi tumbuhan, entomologi dan kejuruteraan pertanian semuanya memerlukan maklumat cuaca. Peringkat 9 kembali kepada pertanian, apabila anda sudah cukup memahami meteorologi untuk mengikuti aplikasinya.",
    src=["PAM:33-34"]),
 ]},
 {"id": "s5", "heading": T("谁在观测和预报天气", "Who watches the weather", "Siapa yang memantau cuaca"), "level": "basic", "blocks": [
  P("天气不分国界，所以气象是最依赖国际合作的科学之一。这门课会反复提到下面几个机构：",
    "Weather ignores borders, so meteorology depends on international cooperation more than most sciences. These organisations come up again and again in this course:",
    "Cuaca tidak mengenal sempadan, jadi meteorologi lebih bergantung pada kerjasama antarabangsa berbanding kebanyakan sains. Organisasi berikut akan disebut berulang kali dalam kursus ini:",
    src=["WMO-75"]),
  {"type": "keyval", "defines": ["wmo"], "src": ["WMO-75", "MET-HOME", "ECMWF-WHO", "NOAA-EMC-GEFS", "JMA-MSC", "ASMC"], "rows": [
   {"k": T("WMO", "WMO", "WMO"), "v": T("{{t:wmo}}：联合国专门机构，有 193 个会员国和地区，制定全球统一的观测和资料交换标准。", "{{t:wmo}}: a United Nations specialised agency with 193 Member States and Territories; it sets the shared standards for observing and exchanging weather data.", "{{t:wmo}}: agensi khusus Pertubuhan Bangsa-Bangsa Bersatu dengan 193 Negara Anggota dan Wilayah; ia menetapkan piawaian bersama untuk mencerap dan bertukar data cuaca.")},
   {"k": T("MetMalaysia", "MetMalaysia", "MetMalaysia"), "v": T("马来西亚气象局：负责马来西亚的天气预报、海洋预报、气候监测，以及地震和海啸信息。", "Malaysian Meteorological Department: weather and marine forecasts, climate monitoring, and earthquake and tsunami information for Malaysia.", "Jabatan Meteorologi Malaysia: ramalan cuaca dan marin, pemantauan iklim, serta maklumat gempa bumi dan tsunami bagi Malaysia.")},
   {"k": T("ECMWF", "ECMWF", "ECMWF"), "v": T("欧洲中期天气预报中心：1975 年成立的独立政府间组织，有 35 个国家支持，在英国 Reading、意大利 Bologna 和德国 Bonn 设有据点，制作全球数值天气预报。第 29 章会专门介绍。", "European Centre for Medium-Range Weather Forecasts: an independent intergovernmental organisation founded in 1975 and supported by 35 states, with sites in Reading (UK), Bologna (Italy) and Bonn (Germany); it produces global numerical weather forecasts. Chapter 29 is about it.", "Pusat Ramalan Cuaca Jangka Sederhana Eropah: organisasi antara kerajaan yang bebas, ditubuhkan pada 1975 dan disokong 35 negara, dengan pejabat di Reading (UK), Bologna (Itali) dan Bonn (Jerman); ia menghasilkan ramalan cuaca berangka global. Bab 29 membincangkannya.")},
   {"k": T("NOAA", "NOAA", "NOAA"), "v": T("美国国家海洋暨大气总署：旗下的模式中心运行全球预报系统 GFS 及其集合预报 GEFS。", "US National Oceanic and Atmospheric Administration: its modelling centre runs the Global Forecast System (GFS) and its ensemble, GEFS.", "Pentadbiran Lautan dan Atmosfera Kebangsaan AS: pusat pemodelannya mengendalikan Sistem Ramalan Global (GFS) dan ensembelnya, GEFS.")},
   {"k": T("JMA", "JMA", "JMA"), "v": T("日本气象厅：运行向日葵（Himawari）气象卫星，马来西亚看的卫星云图主要来自它。", "Japan Meteorological Agency: operates the Himawari weather satellites, the main source of the satellite pictures used in Malaysia.", "Agensi Meteorologi Jepun: mengendalikan satelit cuaca Himawari, sumber utama imej satelit yang digunakan di Malaysia.")},
   {"k": T("ASMC", "ASMC", "ASMC"), "v": T("东盟专门气象中心：1993 年成立，设在新加坡，负责监测东盟地区的森林火灾和跨境烟霾。", "ASEAN Specialised Meteorological Centre: set up in 1993 and hosted in Singapore, it monitors land and forest fires and transboundary haze across ASEAN.", "Pusat Meteorologi Khusus ASEAN: ditubuhkan pada 1993 dan berpangkalan di Singapura, ia memantau kebakaran tanah dan hutan serta jerebu rentas sempadan di seluruh ASEAN.")}]},
 ]},
 {"id": "s6", "heading": T("这门课怎么读", "How this course works", "Cara kursus ini berfungsi"), "level": "basic", "blocks": [
  P("课程分成 9 个阶段、42 章，由浅入深：先认识大气、能量、水和风，再看马来西亚的天气，然后学观测、数值预报和 ECMWF 的模型，最后回到农业。每一章只会用到前面已经讲过的名词。",
    "The course has 9 stages and 42 chapters, from the ground up: first the atmosphere, energy, water and wind; then Malaysia's weather; then observation, numerical forecasting and ECMWF's models; and finally farming. Each chapter only uses terms already explained.",
    "Kursus ini mempunyai 9 peringkat dan 42 bab, bermula dari asas: mula-mula atmosfera, tenaga, air dan angin; kemudian cuaca Malaysia; seterusnya pencerapan, ramalan berangka dan model ECMWF; dan akhirnya pertanian. Setiap bab hanya menggunakan istilah yang sudah diterangkan."),
  L(("带下划虚线的名词可以点开，看一句话的解释和它在哪一章详细讲。", "Terms with a dotted underline can be tapped for a one-line definition and the chapter that explains them.", "Istilah bergaris bawah titik boleh diketik untuk definisi ringkas dan bab yang menerangkannya."),
    ("标着“进阶”的段落收起来了，想深入再点开。", "Sections marked ‘Going deeper’ are folded away; open them when you want more.", "Bahagian bertanda ‘Lanjutan’ dilipat; bukanya apabila anda mahu tahu lebih."),
    ("图表都可以用手指拖动或点选。", "Every chart and figure can be dragged or tapped.", "Setiap carta dan rajah boleh diseret atau diketik."),
    ("每个阶段读完，可以做那个阶段的自测题。", "At the end of each stage there is a self-test.", "Di hujung setiap peringkat ada ujian kendiri.")),
  N("key", "🌦️ 贯穿全课的问题：为什么马来西亚常常早上晴天，下午就下雷阵雨？答案要用到好几章的知识，我们会一块一块拼起来，在第 17 章完成。",
    "🌦️ A question that runs through the course: why is Malaysia so often sunny in the morning and stormy in the afternoon? The answer needs several chapters; we will build it piece by piece and finish it in Chapter 17.",
    "🌦️ Soalan yang merentasi kursus ini: mengapa Malaysia selalunya cerah pada waktu pagi dan ribut pada waktu petang? Jawapannya memerlukan beberapa bab; kita akan membinanya sedikit demi sedikit dan melengkapkannya dalam Bab 17."),
 ]},
 ]}

terms = [
 ("meteorology", T("气象学", "Meteorology", "Meteorologi"), T("研究地球大气及其产生天气的各种过程的科学。", "The science of the Earth's atmosphere and the processes in it that make weather.", "Sains tentang atmosfera Bumi dan proses di dalamnya yang menghasilkan cuaca.")),
 ("weather", T("天气", "Weather", "Cuaca"), T("某地某时的大气状况，随时在变。", "The state of the atmosphere at a given place and time; always changing.", "Keadaan atmosfera di sesuatu tempat dan masa; sentiasa berubah.")),
 ("weather-elements", T("气象要素", "Weather elements", "Unsur cuaca"), T("描述天气的可测量项目：气温、气压、湿度、云、降水、能见度、风。", "The measurable quantities that describe weather: temperature, pressure, humidity, cloud, precipitation, visibility and wind.", "Kuantiti boleh diukur yang menerangkan cuaca: suhu, tekanan, kelembapan, awan, kerpasan, keterlihatan dan angin.")),
 ("climate", T("气候", "Climate", "Iklim"), T("一个地方长期（通常 30 年）的平均天气和极端情况。", "The long-term (usually 30-year) average and extremes of a place's weather.", "Purata dan nilai ekstrem cuaca sesuatu tempat dalam jangka panjang (biasanya 30 tahun).")),
 ("agrometeorology", T("农业气象学", "Agricultural meteorology", "Meteorologi pertanian"), T("研究天气、气候与农业生产关系的学科。", "The study of how weather and climate relate to farming.", "Kajian tentang hubungan cuaca dan iklim dengan pertanian.")),
 ("wmo", T("世界气象组织", "World Meteorological Organization", "Pertubuhan Meteorologi Sedunia"), T("联合国负责天气、气候和水的专门机构，制定全球气象标准。", "The UN specialised agency for weather, climate and water; it sets global standards.", "Agensi khusus PBB bagi cuaca, iklim dan air; ia menetapkan piawaian global."), "WMO"),
]

sources = [
 {"id": "WMO-75", "short": "WMO", "title": "2025 – Celebrating 75 Years of WMO Science for Action", "publisher": "World Meteorological Organization", "url": "https://wmo.int/resources/wmo-bulletin/wmo-bulletin-vol-73-2-2024/2025-celebrating-75-years-of-wmo-science-action", "accessed": "2026-10-02"},
 {"id": "MET-HOME", "short": "MetMalaysia", "title": "Official website of the Malaysian Meteorological Department", "publisher": "MetMalaysia", "url": "https://www.met.gov.my/en/", "accessed": "2026-10-02"},
 {"id": "ECMWF-WHO", "short": "ECMWF", "title": "Who we are", "publisher": "ECMWF", "url": "https://www.ecmwf.int/en/about/who-we-are", "accessed": "2026-10-02"},
 {"id": "NOAA-EMC-GEFS", "short": "NOAA EMC", "title": "Global Ensemble Forecast System (GEFS)", "publisher": "NOAA Environmental Modeling Center", "url": "https://emc.ncep.noaa.gov/emc/pages/numerical_forecast_systems/gefs.php", "accessed": "2026-10-02"},
 {"id": "JMA-MSC", "short": "JMA", "title": "Himawari-8/9 — Meteorological Satellite Center", "publisher": "Japan Meteorological Agency", "url": "https://www.data.jma.go.jp/mscweb/en/himawari89/himawari_cast/himawari_cast.php", "accessed": "2026-10-02"},
 {"id": "ASMC", "short": "ASMC", "title": "About ASMC", "publisher": "ASEAN Specialised Meteorological Centre", "url": "https://asmc.asean.org/asmc-about/", "accessed": "2026-10-02"},
]

quiz = [
 {"stage": 1, "chapter": "ch01",
  "q": T("下面哪一句说的是“气候”而不是“天气”？", "Which of these is about climate rather than weather?", "Yang manakah tentang iklim, bukan cuaca?"),
  "options": [T("吉隆坡今天下午有雷雨", "Kuala Lumpur has a thunderstorm this afternoon", "Kuala Lumpur ada ribut petir petang ini"),
              T("现在风很大", "It is very windy right now", "Angin sangat kuat sekarang"),
              T("东海岸一年中 11 月到 3 月雨最多", "On the east coast, November to March is the wettest part of the year", "Di pantai timur, November hingga Mac ialah waktu paling basah dalam setahun"),
              T("明天早上会有雾", "There will be fog tomorrow morning", "Akan ada kabus esok pagi")],
  "answer": 2, "why": T("气候讲的是长期的规律；其他三句都是某个时间的天气。", "Climate is the long-term pattern; the other three describe the weather at one time.", "Iklim ialah corak jangka panjang; tiga yang lain menerangkan cuaca pada satu masa.")},
 {"stage": 1, "chapter": "ch01",
  "q": T("meteorology 这个词的原意是什么？", "What did the word ‘meteorology’ originally mean?", "Apakah maksud asal perkataan ‘meteorologi’?"),
  "options": [T("研究流星", "The study of meteors", "Kajian tentang meteor"), T("研究天上的东西", "The study of things up above", "Kajian tentang benda di atas"),
              T("研究海洋", "The study of the sea", "Kajian tentang laut"), T("研究星星", "The study of stars", "Kajian tentang bintang")],
  "answer": 1, "why": T("来自希腊文 meteorologia：研究天上的一切现象。", "From the Greek meteorologia: the study of everything seen in the sky.", "Daripada bahasa Yunani meteorologia: kajian tentang segala yang dilihat di langit.")},
]

write_chapter(chapter, terms, sources, quiz)
