"""Chapter 2 — The atmosphere."""
import sys
sys.path.insert(0, 'tools/content')
from build import T, P, L, N, write_chapter

chapter = {"id": "ch02", "num": 2, "stage": 1,
 "title": T("大气层", "The atmosphere", "Atmosfera"),
 "sources": ["PAM", "ESS", "NOAA-GML-CO2", "WHO-UV", "US76"],
 "sections": [
 {"id": "s1", "heading": T("薄薄的一层空气", "A thin skin of air", "Lapisan udara yang nipis"), "level": "basic", "blocks": [
  P("包围地球的这层气体叫做{{t:atmosphere}}。它可以伸到几百公里高，但大约 99 % 的空气都挤在离地面 30 公里以内。如果把地球缩成一个大沙滩球，能让人呼吸的那层空气，比一张纸还薄。",
    "The layer of gas wrapped around the Earth is the {{t:atmosphere}}. It reaches up for hundreds of kilometres, yet about 99 % of the air lies within 30 km of the ground. Shrink the Earth to the size of a large beach ball and the breathable part of its air would be thinner than a sheet of paper.",
    "Lapisan gas yang menyelubungi Bumi ialah {{t:atmosphere}}. Ia mencapai ratusan kilometer ke atas, tetapi kira-kira 99 % udara berada dalam lingkungan 30 km dari permukaan. Jika Bumi dikecilkan sebesar bola pantai, bahagian udara yang boleh dihirup lebih nipis daripada sehelai kertas.",
    defines=["atmosphere"], src=["ESS:4", "PAM:3"]),
  P("这层薄薄的空气提供我们呼吸的氧气和植物需要的二氧化碳，挡住太阳大部分有害的紫外线，也让地球保持适合生物的温度。没有大气，白天和晚上的温差会大得惊人。",
    "This thin layer supplies the oxygen we breathe and the carbon dioxide plants need, blocks most of the Sun's harmful ultraviolet light, and keeps the Earth at a temperature life can bear. Without it, the difference between day and night would be enormous.",
    "Lapisan nipis ini membekalkan oksigen yang kita hirup dan karbon dioksida yang diperlukan tumbuhan, menghalang kebanyakan cahaya ultraungu Matahari yang berbahaya, dan mengekalkan suhu Bumi yang sesuai untuk hidupan. Tanpanya, perbezaan antara siang dan malam akan sangat besar.",
    src=["PAM:4"]),
 ]},
 {"id": "s2", "heading": T("空气是由什么组成的", "What air is made of", "Kandungan udara"), "level": "basic", "blocks": [
  {"type": "table", "src": ["ESS:5", "NOAA-GML-CO2"],
   "caption": T("干燥空气的主要成分（按体积）", "The main gases in dry air (by volume)", "Gas utama dalam udara kering (mengikut isi padu)"),
   "headers": [T("气体", "Gas", "Gas"), T("占比", "Share", "Bahagian")],
   "rows": [[T("氮气 N₂", "Nitrogen N₂", "Nitrogen N₂"), T("78.08 %", "78.08 %", "78.08 %")],
            [T("氧气 O₂", "Oxygen O₂", "Oksigen O₂"), T("20.95 %", "20.95 %", "20.95 %")],
            [T("氩气 Ar", "Argon Ar", "Argon Ar"), T("0.93 %", "0.93 %", "0.93 %")],
            [T("二氧化碳 CO₂", "Carbon dioxide CO₂", "Karbon dioksida CO₂"), T("约 0.043 %（2026 年 6 月：427.6 ppm）", "about 0.043 % (June 2026: 427.6 ppm)", "kira-kira 0.043 % (Jun 2026: 427.6 ppm)")],
            [T("其他（氖、氦、甲烷等）", "Others (neon, helium, methane …)", "Lain-lain (neon, helium, metana …)"), T("微量", "traces", "surih")]]},
  P("另外，空气里还有分量不定的水汽：从几乎没有，到大约 4 %。水是大气里唯一会同时以气体、液体和固体存在的物质，这一点让它成为天气的主角，第 3 阶段会专门讲。",
    "On top of these, air holds a variable amount of water vapour, from almost none to about 4 %. Water is the only substance in the atmosphere found naturally as gas, liquid and solid, which makes it the star of the weather; Stage 3 is about it.",
    "Selain itu, udara mengandungi wap air dalam jumlah berubah-ubah, daripada hampir tiada hingga kira-kira 4 %. Air ialah satu-satunya bahan dalam atmosfera yang wujud secara semula jadi sebagai gas, cecair dan pepejal, menjadikannya watak utama cuaca; Peringkat 3 membincangkannya.",
    src=["ESS:5-6"]),
  N("key", "二氧化碳在增加。你手上的参考书写的还是 0.03 %（较早的数据）和 390 ppm（2010 年版），而美国 NOAA 测得 2026 年 6 月全球平均已达 427.6 ppm。第 15 章会讲这对气候有什么影响。",
    "Carbon dioxide is rising. The reference books say 0.03 % (older data) and 390 ppm (2010 edition); NOAA's global average for June 2026 is 427.6 ppm. Chapter 15 explains what this means for climate.",
    "Karbon dioksida semakin meningkat. Buku rujukan menyebut 0.03 % (data lama) dan 390 ppm (edisi 2010); purata global NOAA bagi Jun 2026 ialah 427.6 ppm. Bab 15 menerangkan kesannya terhadap iklim.",
    src=["PAM:5", "ESS:5", "NOAA-GML-CO2"]),
 ]},
 {"id": "s3", "heading": T("空气有重量：气压", "Air has weight: pressure", "Udara ada berat: tekanan"), "level": "basic", "blocks": [
  P("空气虽然轻，但有重量。头顶上一整柱空气压下来的力，就是{{t:air-pressure}}，常用单位是 hPa（百帕）。海平面的标准气压是 1013.25 hPa。",
    "Air is light but it has weight. The force of the whole column of air above pressing down is {{t:air-pressure}}, usually given in hPa (hectopascals). Standard sea-level pressure is 1013.25 hPa.",
    "Udara ringan tetapi mempunyai berat. Daya seluruh turus udara di atas yang menekan ke bawah ialah {{t:air-pressure}}, biasanya dalam hPa (hektopascal). Tekanan piawai paras laut ialah 1013.25 hPa.",
    defines=["air-pressure"], src=["ESS:10", "PAM:4"]),
  P("越往上，头顶上的空气越少，气压就越低。在大约 5.5 公里高的地方，气压只剩海平面的一半——也就是说，一半的空气都在你脚下了。",
    "The higher you go, the less air is above you, so pressure falls. At about 5.5 km it is only half its sea-level value: half of all the air is below you.",
    "Semakin tinggi, semakin sedikit udara di atas, jadi tekanan jatuh. Pada kira-kira 5.5 km ia hanya separuh nilai paras laut: separuh daripada semua udara berada di bawah anda.",
    src=["ESS:10"]),
 ]},
 {"id": "s4", "heading": T("大气的分层", "The layers", "Lapisan-lapisan"), "level": "basic", "blocks": [
  P("科学家按照“气温怎样随高度变化”把大气分成几层。从地面往上：",
    "Scientists divide the atmosphere into layers by how temperature changes with height. From the ground up:",
    "Saintis membahagikan atmosfera kepada lapisan berdasarkan perubahan suhu dengan ketinggian. Dari permukaan ke atas:",
    src=["PAM:5", "ESS:11"]),
  P("{{t:troposphere}}：最底下的一层，几乎所有的云、雨和风暴都在这里，所以被称为“天气发生的地方”。这里越高越冷，平均每升高 1 公里降约 6.5 °C。它的厚度不一样：赤道上约 16 公里，两极只有 7 到 8 公里。",
    "{{t:troposphere}}: the lowest layer, home to nearly all clouds, rain and storms — ‘where weather happens’. It gets colder with height, by about 6.5 °C per kilometre on average. Its depth varies: about 16 km over the equator, only 7 to 8 km over the poles.",
    "{{t:troposphere}}: lapisan paling bawah, tempat hampir semua awan, hujan dan ribut — ‘tempat cuaca berlaku’. Ia semakin sejuk dengan ketinggian, kira-kira 6.5 °C bagi setiap kilometer secara purata. Ketebalannya berbeza: kira-kira 16 km di khatulistiwa, hanya 7 hingga 8 km di kutub.",
    defines=["troposphere"], src=["PAM:6-7"]),
  P("对流层的顶端叫{{t:tropopause}}，是它和上一层的分界。",
    "The top of the troposphere is the {{t:tropopause}}, the boundary with the layer above.",
    "Bahagian atas troposfera ialah {{t:tropopause}}, sempadan dengan lapisan di atasnya.",
    defines=["tropopause"], src=["PAM:7"]),
  P("{{t:stratosphere}}：从对流层顶到约 50 公里。这里越高反而越暖，因为臭氧吸收了太阳的紫外线而发热。空气在这里很少上下翻腾，所以分层很稳定。",
    "{{t:stratosphere}}: from the tropopause to about 50 km. Here it gets warmer with height, because ozone absorbs the Sun's ultraviolet light and heats the air. The air hardly overturns, so it stays neatly layered.",
    "{{t:stratosphere}}: dari tropopaus hingga kira-kira 50 km. Di sini suhu meningkat dengan ketinggian, kerana ozon menyerap cahaya ultraungu Matahari dan memanaskan udara. Udara hampir tidak berpusing, jadi ia kekal berlapis.",
    defines=["stratosphere"], src=["PAM:7-8", "ESS:13"]),
  P("{{t:mesosphere}}：约 50 到 85 公里，又是越高越冷。它的顶端平均约 −90 °C，是整个大气里最冷的地方。",
    "{{t:mesosphere}}: from about 50 to 85 km, colder with height again. Its top averages about −90 °C, the coldest part of the whole atmosphere.",
    "{{t:mesosphere}}: kira-kira 50 hingga 85 km, semakin sejuk dengan ketinggian semula. Bahagian atasnya purata kira-kira −90 °C, bahagian paling sejuk seluruh atmosfera.",
    defines=["mesosphere"], src=["PAM:8", "ESS:13"]),
  P("{{t:thermosphere}}：约 85 公里以上。这里的氧分子吸收高能量的太阳辐射，气温可以超过 500 °C。但空气极其稀薄，就算在那里也不会觉得热：根本没有足够的分子撞到你身上把热传过来。",
    "{{t:thermosphere}}: above about 85 km. Oxygen molecules absorb energetic solar radiation and the temperature can exceed 500 °C. Yet the air is so thin you would not feel hot: too few molecules bump into you to pass the heat on.",
    "{{t:thermosphere}}: di atas kira-kira 85 km. Molekul oksigen menyerap sinaran suria bertenaga dan suhu boleh melebihi 500 °C. Namun udara begitu nipis sehingga anda tidak akan berasa panas: terlalu sedikit molekul yang berlanggar dengan anda untuk memindahkan haba.",
    defines=["thermosphere"], src=["ESS:13"]),
  {"type": "widget", "id": "W1"},
  N("tip", "马来西亚在赤道附近，对流层比标准大气更厚，对流层顶大约在 16 公里高。热带的雷雨云可以长得非常高，就是因为这里的对流层特别深。",
    "Malaysia is near the equator, where the troposphere is deeper than the standard atmosphere: the tropopause is at about 16 km. That depth is one reason tropical thunderclouds can grow so tall.",
    "Malaysia berhampiran khatulistiwa, di mana troposfera lebih tebal daripada atmosfera piawai: tropopaus berada kira-kira 16 km. Ketebalan itu salah satu sebab awan ribut tropika boleh tumbuh begitu tinggi.",
    src=["PAM:6"]),
 ]},
 {"id": "s5", "heading": T("臭氧层与紫外线", "The ozone layer and UV", "Lapisan ozon dan UV"), "level": "basic", "blocks": [
  P("大气里约 97 % 的臭氧都在平流层，这一层叫{{t:ozone-layer}}。臭氧很少，但它吸收了太阳最有害的紫外线，保护地面上的植物、动物和人。地面附近的臭氧却是光化学烟雾的主要成分，会刺激眼睛和喉咙、伤害作物。",
    "About 97 % of the atmosphere's ozone is in the stratosphere, in what is called the {{t:ozone-layer}}. There is very little of it, but it absorbs the Sun's most harmful ultraviolet light and shields plants, animals and people. Near the ground, by contrast, ozone is the main ingredient of photochemical smog: it irritates eyes and throats and damages crops.",
    "Kira-kira 97 % ozon atmosfera berada di stratosfera, dalam apa yang dipanggil {{t:ozone-layer}}. Jumlahnya sangat sedikit, tetapi ia menyerap cahaya ultraungu Matahari yang paling berbahaya dan melindungi tumbuhan, haiwan dan manusia. Berhampiran permukaan pula, ozon ialah bahan utama asbut fotokimia: ia merengsakan mata dan tekak serta merosakkan tanaman.",
    defines=["ozone-layer"], src=["ESS:8"]),
  P("天气预报里的{{t:uv-index}}告诉你当天紫外线有多强。世界卫生组织的建议是：",
    "The {{t:uv-index}} in a forecast tells you how strong the day's ultraviolet light will be. The World Health Organization advises:",
    "{{t:uv-index}} dalam ramalan memberitahu betapa kuat cahaya ultraungu hari itu. Pertubuhan Kesihatan Sedunia menasihatkan:",
    defines=["uv-index"], src=["WHO-UV"]),
  {"type": "table", "src": ["WHO-UV"],
   "caption": T("世界卫生组织的紫外线指数建议", "WHO advice by UV index", "Nasihat WHO mengikut indeks UV"),
   "headers": [T("紫外线指数", "UV index", "Indeks UV"), T("建议", "Advice", "Nasihat")],
   "rows": [[T("0–2", "0–2", "0–2"), T("可以放心在户外", "Safe to be outside", "Selamat berada di luar")],
            [T("3–7", "3–7", "3–7"), T("中午前后找阴凉处；穿上衣、擦防晒、戴帽子", "Seek shade around midday; shirt, sunscreen and hat", "Cari teduh sekitar tengah hari; baju, pelindung matahari dan topi")],
            [T("8 以上", "8 and above", "8 ke atas"), T("中午前后避免待在户外；上衣、防晒、帽子都必须", "Avoid being outside around midday; shirt, sunscreen and hat are a must", "Elakkan berada di luar sekitar tengah hari; baju, pelindung matahari dan topi wajib")]]},
 ]},
 {"id": "s6", "heading": T("按成分和电离来分", "Layers by make-up and by charge", "Lapisan mengikut kandungan dan cas"), "level": "advanced", "blocks": [
  P("也可以按成分来分：一直到热层的底部，空气被不停搅拌，成分几乎一样（78 % 氮、21 % 氧），叫均质层；再往上分子很少碰撞，较重的气体沉在下面、较轻的浮在上面，叫非均质层。",
    "The atmosphere can also be divided by make-up. Up to the bottom of the thermosphere the air is constantly stirred and its composition hardly changes (78 % nitrogen, 21 % oxygen): the homosphere. Above that, molecules rarely collide, heavier gases settle and lighter ones float up: the heterosphere.",
    "Atmosfera juga boleh dibahagikan mengikut kandungan. Sehingga bahagian bawah termosfera, udara sentiasa dikacau dan komposisinya hampir tidak berubah (78 % nitrogen, 21 % oksigen): homosfera. Di atasnya, molekul jarang berlanggar, gas berat mendap dan gas ringan terapung: heterosfera.",
    src=["ESS:14"]),
  P("从大约 60 公里往上，太阳辐射把原子打成带电的离子，这一带叫电离层，大部分在热层里。电离层会反射无线电波，所以远距离的短波和中波广播传得到。最外面约 400 到 1000 公里是外逸层，主要是氢和氦，原子稀少到几乎不会互相碰撞。",
    "From about 60 km up, solar radiation strips electrons from atoms and leaves charged ions: this is the ionosphere, mostly within the thermosphere. It reflects radio waves, which is how long-distance AM and shortwave broadcasts travel. Outermost, from about 400 to 1,000 km, is the exosphere, mainly hydrogen and helium, so thin that atoms almost never collide.",
    "Dari kira-kira 60 km ke atas, sinaran suria melucutkan elektron daripada atom dan meninggalkan ion bercas: inilah ionosfera, kebanyakannya dalam termosfera. Ia memantulkan gelombang radio, itulah cara siaran AM dan gelombang pendek jarak jauh bergerak. Paling luar, kira-kira 400 hingga 1,000 km, ialah eksosfera, terutamanya hidrogen dan helium, begitu nipis sehingga atom hampir tidak pernah berlanggar.",
    src=["ESS:14", "PAM:8"]),
 ]},
 ]}

terms = [
 ("atmosphere", T("大气", "Atmosphere", "Atmosfera"), T("包围地球的一层气体；约 99 % 在离地 30 公里以内。", "The layer of gas around the Earth; about 99 % of it lies within 30 km of the ground.", "Lapisan gas yang menyelubungi Bumi; kira-kira 99 % berada dalam 30 km dari permukaan.")),
 ("air-pressure", T("气压", "Air pressure", "Tekanan udara"), T("上方空气的重量压下来的力，单位 hPa；海平面标准值 1013.25 hPa。", "The force of the air above pressing down, in hPa; 1013.25 hPa at standard sea level.", "Daya udara di atas yang menekan ke bawah, dalam hPa; 1013.25 hPa pada paras laut piawai.")),
 ("troposphere", T("对流层", "Troposphere", "Troposfera"), T("最底下的一层，天气都发生在这里；越高越冷。", "The lowest layer, where weather happens; colder with height.", "Lapisan paling bawah, tempat cuaca berlaku; semakin sejuk dengan ketinggian.")),
 ("tropopause", T("对流层顶", "Tropopause", "Tropopaus"), T("对流层和平流层的分界；热带约 16 公里高。", "The boundary between troposphere and stratosphere; about 16 km high in the tropics.", "Sempadan antara troposfera dan stratosfera; kira-kira 16 km di kawasan tropika.")),
 ("stratosphere", T("平流层", "Stratosphere", "Stratosfera"), T("对流层之上到约 50 公里；臭氧吸收紫外线使它越高越暖。", "From the tropopause to about 50 km; ozone absorbing UV makes it warmer with height.", "Dari tropopaus hingga kira-kira 50 km; ozon yang menyerap UV menjadikannya lebih panas dengan ketinggian.")),
 ("mesosphere", T("中间层", "Mesosphere", "Mesosfera"), T("约 50–85 公里，越高越冷；顶端是大气最冷处。", "About 50–85 km, colder with height; its top is the coldest part of the atmosphere.", "Kira-kira 50–85 km, semakin sejuk dengan ketinggian; bahagian atasnya paling sejuk dalam atmosfera.")),
 ("thermosphere", T("热层", "Thermosphere", "Termosfera"), T("约 85 公里以上；空气极稀薄，温度却可超过 500 °C。", "Above about 85 km; extremely thin air that can exceed 500 °C.", "Di atas kira-kira 85 km; udara sangat nipis yang boleh melebihi 500 °C.")),
 ("ozone-layer", T("臭氧层", "Ozone layer", "Lapisan ozon"), T("平流层中臭氧集中的部分，吸收太阳有害的紫外线。", "The ozone-rich part of the stratosphere that absorbs the Sun's harmful ultraviolet light.", "Bahagian stratosfera yang kaya ozon dan menyerap cahaya ultraungu Matahari yang berbahaya.")),
 ("uv-index", T("紫外线指数", "UV index", "Indeks UV"), T("表示当天紫外线强度的数字；3 以上要防晒，8 以上中午避免外出。", "A number for the day's ultraviolet strength; protect yourself from 3, avoid the midday sun from 8.", "Nombor bagi kekuatan ultraungu hari itu; lindungi diri dari 3, elakkan matahari tengah hari dari 8."), "UV"),
]

sources = [
 {"id": "NOAA-GML-CO2", "short": "NOAA GML", "title": "Trends in Atmospheric Carbon Dioxide — Global", "publisher": "NOAA Global Monitoring Laboratory", "url": "https://gml.noaa.gov/ccgg/trends/global.html", "accessed": "2026-10-02"},
 {"id": "WHO-UV", "short": "WHO", "title": "Radiation: The ultraviolet (UV) index", "publisher": "World Health Organization", "url": "https://www.who.int/news-room/questions-and-answers/item/radiation-the-ultraviolet-(uv)-index", "accessed": "2026-10-02"},
 {"id": "US76", "short": "US Std Atm 1976", "title": "U.S. Standard Atmosphere, 1976", "publisher": "NOAA, NASA and US Air Force, 1976", "url": "", "accessed": ""},
]

quiz = [
 {"stage": 1, "chapter": "ch02",
  "q": T("为什么平流层是越高越暖？", "Why does the stratosphere get warmer with height?", "Mengapa stratosfera semakin panas dengan ketinggian?"),
  "options": [T("它离太阳比较近", "It is closer to the Sun", "Ia lebih dekat dengan Matahari"), T("臭氧吸收紫外线而发热", "Ozone absorbs ultraviolet light and heats the air", "Ozon menyerap cahaya ultraungu dan memanaskan udara"),
              T("地面的热传上去", "Heat rises from the ground", "Haba naik dari permukaan"), T("那里的空气比较密", "The air there is denser", "Udara di sana lebih tumpat")],
  "answer": 1, "why": T("平流层里的臭氧吸收了紫外线的能量，把空气加热。", "Ozone in the stratosphere absorbs ultraviolet energy and warms the air.", "Ozon di stratosfera menyerap tenaga ultraungu dan memanaskan udara.")},
 {"stage": 1, "chapter": "ch02",
  "q": T("在大约多高的地方，一半的空气已经在你下面？", "Roughly how high must you be for half the air to be below you?", "Pada ketinggian kira-kira berapa separuh udara berada di bawah anda?"),
  "options": [T("1 公里", "1 km", "1 km"), T("5.5 公里", "5.5 km", "5.5 km"), T("30 公里", "30 km", "30 km"), T("100 公里", "100 km", "100 km")],
  "answer": 1, "why": T("约 5.5 公里处气压约 500 hPa，只有海平面的一半。", "At about 5.5 km the pressure is near 500 hPa, half its sea-level value.", "Pada kira-kira 5.5 km tekanan hampir 500 hPa, separuh nilai paras laut.")},

 {"stage": 1, "chapter": "ch02",
  "q": T("几乎所有的云和雨都发生在哪一层？", "In which layer do nearly all clouds and rain occur?", "Dalam lapisan manakah hampir semua awan dan hujan berlaku?"),
  "options": [T("对流层", "Troposphere", "Troposfera"), T("平流层", "Stratosphere", "Stratosfera"), T("中间层", "Mesosphere", "Mesosfera"), T("热层", "Thermosphere", "Termosfera")],
  "answer": 0, "why": T("对流层集中了几乎所有的水汽，是天气发生的地方。", "The troposphere holds almost all the water vapour; it is where weather happens.", "Troposfera mengandungi hampir semua wap air; di situlah cuaca berlaku.")},
 {"stage": 1, "chapter": "ch02",
  "q": T("紫外线指数是 9，世界卫生组织建议怎么做？", "The UV index is 9. What does the WHO advise?", "Indeks UV ialah 9. Apakah nasihat WHO?"),
  "options": [T("可以放心在户外", "It is safe to be outside", "Selamat berada di luar"), T("只需要戴太阳眼镜", "Sunglasses are enough", "Cermin mata hitam sudah memadai"),
              T("中午前后避免外出，上衣、防晒和帽子都必须", "Avoid the midday sun; shirt, sunscreen and hat are a must", "Elakkan matahari tengah hari; baju, pelindung matahari dan topi wajib"), T("晚上才需要防晒", "Protection is only needed at night", "Perlindungan hanya perlu pada waktu malam")],
  "answer": 2, "why": T("8 以上属于最高的一级：中午前后应避免待在户外。", "8 and above is the top band: avoid being outside around midday.", "8 ke atas ialah jalur tertinggi: elakkan berada di luar sekitar tengah hari.")},
]

write_chapter(chapter, terms, sources, quiz)
