"""Chapter 3 — Solar radiation and the energy balance."""
import sys
sys.path.insert(0, 'tools/content')
from build import T, P, L, N, write_chapter

chapter = {"id": "ch03", "num": 3, "stage": 2,
 "title": T("太阳辐射与能量平衡", "Solar radiation and the energy balance", "Sinaran suria dan imbangan tenaga"),
 "sources": ["PAM", "ESS", "NOAA-EOT"],
 "sections": [
 {"id": "s1", "heading": T("能量从太阳来", "Energy from the Sun", "Tenaga dari Matahari"), "level": "basic", "blocks": [
  P("几乎所有推动天气的能量都来自太阳。太阳以电磁波的形式向外送出能量，叫做{{t:radiation}}；它以每秒约 30 万公里的光速穿过真空，大约 8 分钟到达地球。辐射是唯一不需要任何物质就能传递能量的方式。",
    "Almost all the energy that drives the weather comes from the Sun. The Sun sends it out as electromagnetic waves — {{t:radiation}} — travelling through empty space at the speed of light, about 300,000 km per second, and reaching the Earth in about eight minutes. Radiation is the only way of carrying energy that needs no material at all.",
    "Hampir semua tenaga yang menggerakkan cuaca datang dari Matahari. Matahari menghantarnya sebagai gelombang elektromagnet — {{t:radiation}} — yang bergerak melalui ruang kosong pada kelajuan cahaya, kira-kira 300,000 km sesaat, dan sampai ke Bumi dalam kira-kira lapan minit. Sinaran ialah satu-satunya cara memindahkan tenaga yang tidak memerlukan bahan langsung.",
    defines=["radiation"], src=["PAM:42-43"]),
  P("热量还有另外两种传递方式：传导（热沿着物体本身从热的一端传到冷的一端，例如烫手的铁棒）和对流（受热的流体自己移动，把热带走，例如烧开水时水在锅里翻滚）。天气里最重要的是对流，第 7 章会详细讲。",
    "Heat moves in two other ways too: conduction, through a material from hot to cold (an iron rod heating along its length), and convection, where heated fluid moves and carries the heat with it (water churning in a boiling pot). In the weather, convection matters most; Chapter 7 is about it.",
    "Haba juga bergerak dengan dua cara lain: konduksi, melalui bahan dari panas ke sejuk (batang besi yang memanas sepanjangnya), dan perolakan, apabila bendalir yang dipanaskan bergerak dan membawa haba bersamanya (air bergolak dalam periuk mendidih). Dalam cuaca, perolakan paling penting; Bab 7 membincangkannya.",
    src=["PAM:43"]),
 ]},
 {"id": "s2", "heading": T("短波与长波", "Short waves and long waves", "Gelombang pendek dan gelombang panjang"), "level": "basic", "blocks": [
  P("所有温度在绝对零度以上的东西都会发出辐射。东西越热，发出的辐射越强，波长也越短。太阳表面非常热，它发出的能量集中在约 0.5 微米的可见光附近，叫{{t:shortwave}}。",
    "Everything warmer than absolute zero gives off radiation. The hotter it is, the more it emits and the shorter its wavelengths. The Sun's surface is extremely hot, so its energy peaks near 0.5 micrometres, in visible light: {{t:shortwave}}.",
    "Semua benda yang lebih panas daripada sifar mutlak memancarkan sinaran. Semakin panas, semakin banyak dipancarkan dan semakin pendek panjang gelombangnya. Permukaan Matahari sangat panas, jadi tenaganya memuncak berhampiran 0.5 mikrometer, dalam cahaya nampak: {{t:shortwave}}.",
    defines=["shortwave"], src=["PAM:50-51", "ESS:35"]),
  P("地球、云、空气和你自己都比太阳冷得多，发出的是看不见的红外线，波长约 10 微米，叫{{t:longwave}}。天气的能量故事，就是“短波进来、长波出去”。",
    "The Earth, clouds, air — and you — are far cooler than the Sun and give off invisible infrared around 10 micrometres: {{t:longwave}}. The energy story of the weather is short waves in, long waves out.",
    "Bumi, awan, udara — dan anda — jauh lebih sejuk daripada Matahari dan memancarkan inframerah yang tidak kelihatan sekitar 10 mikrometer: {{t:longwave}}. Kisah tenaga cuaca ialah gelombang pendek masuk, gelombang panjang keluar.",
    defines=["longwave"], src=["ESS:35"]),
 ]},
 {"id": "s2a", "heading": T("辐射定律", "The radiation laws", "Hukum sinaran"), "level": "advanced", "blocks": [
  {"type": "keyval", "src": ["PAM:50-51", "ESS:35"], "rows": [
   {"k": T("维恩定律", "Wien's law", "Hukum Wien"), "v": T("发射最强的波长 λmax ≈ 2897 ÷ T 微米（T 用开尔文）。太阳约 5800 K → 约 0.5 微米；地面约 288 K → 约 10 微米。", "Wavelength of strongest emission λmax ≈ 2897 ÷ T micrometres (T in kelvin). The Sun at about 5800 K → about 0.5 µm; the ground at about 288 K → about 10 µm.", "Panjang gelombang pancaran terkuat λmax ≈ 2897 ÷ T mikrometer (T dalam kelvin). Matahari kira-kira 5800 K → kira-kira 0.5 µm; tanah kira-kira 288 K → kira-kira 10 µm.")},
   {"k": T("斯特藩–玻尔兹曼定律", "Stefan–Boltzmann law", "Hukum Stefan–Boltzmann"), "v": T("每平方米发出的能量 E = σT⁴，σ = 5.67 × 10⁻⁸ W/m²/K⁴。温度加倍，发出的能量变成 16 倍。", "Energy emitted per square metre E = σT⁴, with σ = 5.67 × 10⁻⁸ W/m²/K⁴. Double the temperature and the emission rises sixteenfold.", "Tenaga dipancarkan bagi setiap meter persegi E = σT⁴, dengan σ = 5.67 × 10⁻⁸ W/m²/K⁴. Gandakan suhu dan pancaran meningkat enam belas kali.")},
   {"k": T("基尔霍夫定律", "Kirchhoff's law", "Hukum Kirchhoff"), "v": T("一样东西对某个波长吸收得好，对那个波长也发射得好。", "Something that absorbs a wavelength well also emits it well.", "Sesuatu yang menyerap sesuatu panjang gelombang dengan baik juga memancarkannya dengan baik.")}]},
 ]},
 {"id": "s3", "heading": T("阳光到了以后", "What happens to sunlight", "Apa yang berlaku kepada cahaya matahari"), "level": "basic", "blocks": [
  P("阳光穿过大气时，一部分笔直照到地面，叫{{t:direct-radiation}}；另一部分被空气分子、尘埃和云撞来撞去，从四面八方散射下来，叫{{t:diffuse-radiation}}。阴天也晒得黑、太阳能板也能发电，靠的就是散射辐射。",
    "As sunlight crosses the atmosphere, some of it reaches the ground in a straight line — {{t:direct-radiation}}; the rest is bounced about by air molecules, dust and cloud and arrives from every direction — {{t:diffuse-radiation}}. Diffuse light is why you can get sunburnt on a cloudy day and why solar panels still produce power.",
    "Apabila cahaya matahari melalui atmosfera, sebahagiannya sampai ke tanah dalam garis lurus — {{t:direct-radiation}}; selebihnya dipantul-pantulkan oleh molekul udara, debu dan awan lalu tiba dari semua arah — {{t:diffuse-radiation}}. Cahaya terserak menyebabkan kulit boleh terbakar walaupun mendung dan panel suria masih menjana kuasa.",
    defines=["direct-radiation", "diffuse-radiation"], src=["PAM:45", "ESS:44"]),
  P("一个表面把照到它的阳光反射掉的比例，叫{{t:albedo}}。新雪可以反射 75–95 %，厚云 60–90 %；森林只有 3–10 %，水面约 10 %。颜色越深、越粗糙，反照率越低，吸收的热越多。",
    "The share of incoming sunlight a surface reflects is its {{t:albedo}}. Fresh snow reflects 75–95 %, thick cloud 60–90 %; forest only 3–10 % and water about 10 %. The darker and rougher a surface, the lower its albedo and the more heat it absorbs.",
    "Bahagian cahaya matahari yang dipantulkan oleh sesuatu permukaan ialah {{t:albedo}}nya. Salji baharu memantulkan 75–95 %, awan tebal 60–90 %; hutan hanya 3–10 % dan air kira-kira 10 %. Semakin gelap dan kasar permukaan, semakin rendah albedonya dan semakin banyak haba diserap.",
    defines=["albedo"], src=["ESS:44"]),
  {"type": "table", "src": ["ESS:44", "PAM:50"],
   "caption": T("几种表面的反照率", "Albedo of some surfaces", "Albedo beberapa permukaan"),
   "headers": [T("表面", "Surface", "Permukaan"), T("反照率", "Albedo", "Albedo")],
   "rows": [[T("新雪", "Fresh snow", "Salji baharu"), T("75–95 %", "75–95 %", "75–95 %")],
            [T("厚云", "Thick cloud", "Awan tebal"), T("60–90 %", "60–90 %", "60–90 %")],
            [T("沙地", "Sand", "Pasir"), T("15–45 %", "15–45 %", "15–45 %")],
            [T("一般作物", "Crops in general", "Tanaman umum"), T("23–25 %", "23–25 %", "23–25 %")],
            [T("草地", "Grassland", "Padang rumput"), T("10–30 %", "10–30 %", "10–30 %")],
            [T("淹水的稻田", "Flooded rice field", "Sawah bertakung"), T("12 %", "12 %", "12 %")],
            [T("水面（日平均）", "Water (daily average)", "Air (purata harian)"), T("10 %", "10 %", "10 %")],
            [T("森林", "Forest", "Hutan"), T("3–10 %", "3–10 %", "3–10 %")],
            [T("地球和大气整体", "Earth and atmosphere together", "Bumi dan atmosfera keseluruhan"), T("30 %", "30 %", "30 %")]]},
  P("一年平均下来，地球和大气接收的能量和送走的能量刚好相等，这叫{{t:energy-balance}}。把到达大气顶端的阳光算成 100：30 被反射回太空，19 被大气和云吸收，51 被地面吸收。下图可以一条一条点开看。",
    "Averaged over a year, the energy the Earth and its atmosphere receive equals the energy they send away: the {{t:energy-balance}}. Call the sunlight reaching the top of the atmosphere 100: 30 is reflected back to space, 19 is absorbed by the air and clouds, and 51 by the surface. Tap through the arrows below.",
    "Dipuratakan sepanjang tahun, tenaga yang diterima Bumi dan atmosferanya sama dengan tenaga yang dihantar keluar: {{t:energy-balance}}. Anggap cahaya matahari di bahagian atas atmosfera 100: 30 dipantulkan kembali ke angkasa, 19 diserap udara dan awan, dan 51 oleh permukaan. Ketik setiap anak panah di bawah.",
    defines=["energy-balance"], src=["ESS:44-45"]),
  {"type": "widget", "id": "W3"},
  P("地面拿到的 51 怎样用掉？23 用来把水蒸发成水汽，这部分热暂时“藏”起来，叫{{t:latent-heat}}，等水汽在高空凝结成云时才放出来；7 直接加热贴地的空气，叫{{t:sensible-heat}}；其余以红外线形式送出。",
    "How are the surface's 51 units spent? 23 evaporate water, and that heat is stored out of sight — {{t:latent-heat}} — until the vapour condenses into cloud high up; 7 heat the air touching the ground directly — {{t:sensible-heat}}; the rest leaves as infrared.",
    "Bagaimana 51 unit permukaan digunakan? 23 menyejatkan air, dan haba itu tersimpan tanpa kelihatan — {{t:latent-heat}} — sehingga wap terkondensasi menjadi awan di atas; 7 memanaskan udara yang menyentuh tanah secara terus — {{t:sensible-heat}}; selebihnya keluar sebagai inframerah.",
    defines=["latent-heat", "sensible-heat"], src=["ESS:44", "PAM:47-48"]),
 ]},
 {"id": "s4", "heading": T("温室效应", "The greenhouse effect", "Kesan rumah hijau"), "level": "basic", "blocks": [
  P("阳光（短波）大多能穿过大气，但地面发出的红外线（长波）大部分被水汽、二氧化碳、甲烷、一氧化二氮、臭氧和云吸收，它们再把一部分热送回地面。这就是{{t:greenhouse-effect}}。没有它，地球平均温度会是约 −15 °C，而不是 +15 °C。",
    "Sunlight (short waves) passes through the atmosphere fairly freely, but most of the infrared (long waves) from the ground is absorbed by water vapour, carbon dioxide, methane, nitrous oxide, ozone and clouds, which send part of it back down. This is the {{t:greenhouse-effect}}. Without it the Earth would average about −15 °C instead of +15 °C.",
    "Cahaya matahari (gelombang pendek) melalui atmosfera dengan agak bebas, tetapi kebanyakan inframerah (gelombang panjang) dari tanah diserap oleh wap air, karbon dioksida, metana, nitrus oksida, ozon dan awan, yang menghantar sebahagiannya kembali ke bawah. Inilah {{t:greenhouse-effect}}. Tanpanya Bumi akan berpurata kira-kira −15 °C, bukan +15 °C.",
    defines=["greenhouse-effect"], src=["PAM:53-54", "ESS:39"]),
  N("myth", "温室效应本身不是坏事，没有它地球会冻结。问题是人类排放的二氧化碳让它变强，地球因此变暖。第 15 章会讲。",
    "The greenhouse effect itself is not a bad thing: without it the Earth would freeze. The problem is that human carbon dioxide is making it stronger, and the planet is warming. Chapter 15 covers this.",
    "Kesan rumah hijau itu sendiri bukan perkara buruk: tanpanya Bumi akan membeku. Masalahnya, karbon dioksida daripada manusia menjadikannya lebih kuat dan planet ini semakin panas. Bab 15 membincangkannya.",
    src=["PAM:55"]),
  P("云在晚上像一张被子：它吸收地面的红外线，又发回地面，所以有云的晚上比晴朗的晚上暖。白天云又挡住阳光，所以阴天白天比较凉。",
    "At night clouds act like a blanket, absorbing the ground's infrared and sending it back, so cloudy nights are warmer than clear ones. By day they block sunlight, so cloudy days are cooler.",
    "Pada waktu malam awan bertindak seperti selimut, menyerap inframerah dari tanah dan menghantarnya kembali, jadi malam berawan lebih panas daripada malam cerah. Pada siang hari awan menghalang cahaya matahari, jadi hari berawan lebih sejuk.",
    src=["ESS:39"]),
 ]},
 {"id": "s5", "heading": T("四季，以及赤道附近为什么没有四季", "Seasons — and why the equator hardly has them", "Musim — dan mengapa khatulistiwa hampir tiada musim"), "level": "basic", "blocks": [
  N("myth", "四季不是因为地球离太阳时近时远。地球其实在 1 月初最靠近太阳（约 1.47 亿公里），7 月初最远（约 1.52 亿公里），但北半球 1 月是冬天。",
    "Seasons are not caused by the Earth's changing distance from the Sun. The Earth is actually closest in early January (about 147 million km) and farthest in early July (about 152 million km), yet January is winter in the Northern Hemisphere.",
    "Musim bukan disebabkan oleh perubahan jarak Bumi dari Matahari. Bumi sebenarnya paling dekat pada awal Januari (kira-kira 147 juta km) dan paling jauh pada awal Julai (kira-kira 152 juta km), namun Januari ialah musim sejuk di Hemisfera Utara.",
    src=["ESS:46"]),
  P("真正的原因是地球的自转轴倾斜了约 23½°。一年中太阳轮流直射北半球和南半球：太阳越高，阳光越集中；白天越长，收到的能量越多。6 月 21 日前后太阳直射北纬 23½°，12 月 21 日前后直射南纬 23½°，3 月和 9 月直射赤道。",
    "The real reason is that the Earth's axis is tilted by about 23½°. Through the year the Sun shines most directly on the Northern and then the Southern Hemisphere: a higher Sun concentrates its light, and a longer day delivers more of it. Around 21 June the noon Sun is overhead at 23½°N, around 21 December at 23½°S, and in March and September over the equator.",
    "Sebab sebenar ialah paksi Bumi condong kira-kira 23½°. Sepanjang tahun Matahari menyinari Hemisfera Utara dan kemudian Selatan secara paling terus: Matahari yang lebih tinggi menumpukan cahayanya, dan siang yang lebih panjang membawa lebih banyak tenaga. Sekitar 21 Jun Matahari tengah hari tegak di atas 23½°U, sekitar 21 Disember di atas 23½°S, dan pada Mac serta September di atas khatulistiwa.",
    src=["ESS:49-50", "PAM:44"]),
  P("马来西亚就在赤道以北不远。这里一年到头白天都约 12 小时，正午太阳都很高，一年还有两次太阳会正好在头顶。所以赤道附近没有明显的冷热四季；我们的“季节”主要是雨季和旱季，由风决定（第 16 章）。",
    "Malaysia lies just north of the equator. Here the day is close to 12 hours long all year, the noon Sun is always high, and twice a year it passes straight overhead. That is why there is no real hot-and-cold cycle of seasons near the equator; our ‘seasons’ are wetter and drier spells, set by the winds (Chapter 16).",
    "Malaysia terletak tidak jauh di utara khatulistiwa. Di sini siang hampir 12 jam sepanjang tahun, Matahari tengah hari sentiasa tinggi, dan dua kali setahun ia melintas tegak di atas kepala. Itulah sebabnya tiada kitaran musim panas dan sejuk yang ketara berhampiran khatulistiwa; ‘musim’ kita ialah tempoh lebih basah dan lebih kering, ditentukan oleh angin (Bab 16).",
    src=["ESS:49-50"]),
  {"type": "widget", "id": "W2"},
  N("tip", "在吉隆坡，太阳最高的时刻不是 12 点，而是下午 1 点多。马来西亚用的是东经 120° 的时区（UTC+8），但吉隆坡在东经约 101.7°，太阳要晚一个多小时才走到正南（或正北）方。",
    "In Kuala Lumpur the Sun is highest not at 12 noon but after 1 pm. Malaysia keeps the time zone of longitude 120°E (UTC+8), while Kuala Lumpur lies near 101.7°E, so the Sun reaches its highest point more than an hour later by the clock.",
    "Di Kuala Lumpur, Matahari paling tinggi bukan pada jam 12 tengah hari tetapi selepas jam 1 petang. Malaysia menggunakan zon waktu longitud 120°T (UTC+8), sedangkan Kuala Lumpur terletak kira-kira 101.7°T, jadi Matahari mencapai titik tertingginya lebih sejam kemudian mengikut jam.",
    src=["NOAA-EOT"]),
 ]},
 {"id": "s6", "heading": T("地面的能量账：净辐射", "The surface energy account: net radiation", "Akaun tenaga permukaan: sinaran bersih"), "level": "advanced", "blocks": [
  P("地面收到的短波减去反射掉的，再减去净送出的长波，叫净辐射 Rn = Rs(1 − r) − RL。白天 Rn 是正的，晚上没有阳光，Rn 是负的，地面一直在失热。",
    "Incoming shortwave minus what is reflected, minus the net longwave lost, is the net radiation Rn = Rs(1 − r) − RL. By day Rn is positive; at night there is no sunlight, Rn is negative and the ground keeps losing heat.",
    "Gelombang pendek masuk tolak yang dipantulkan, tolak gelombang panjang bersih yang hilang, ialah sinaran bersih Rn = Rs(1 − r) − RL. Pada siang hari Rn positif; pada waktu malam tiada cahaya matahari, Rn negatif dan tanah terus kehilangan haba.",
    src=["PAM:46-48"]),
  P("净辐射被分成三份：加热空气的感热 H、蒸发水的潜热 LE、传进土里的地热 G，即 Rn = H + LE + G。在理想的裸地上大约是感热 57 %、潜热 30 %、地热 13 %。土越湿，潜热占得越多；水面上潜热大于感热；沙漠几乎没有潜热。",
    "Net radiation is shared three ways — sensible heat H warming the air, latent heat LE evaporating water and ground heat G conducted into the soil — so Rn = H + LE + G. On ideal bare ground the split is roughly 57 % sensible, 30 % latent, 13 % ground. Wetter soil shifts more into latent heat; over water latent exceeds sensible; in a desert there is almost none.",
    "Sinaran bersih dibahagi tiga — haba deria H memanaskan udara, haba pendam LE menyejatkan air dan haba tanah G dikonduksi ke dalam tanah — jadi Rn = H + LE + G. Di atas tanah terdedah yang ideal, pembahagiannya kira-kira 57 % deria, 30 % pendam, 13 % tanah. Tanah lebih basah mengalihkan lebih banyak ke haba pendam; di atas air haba pendam melebihi haba deria; di gurun hampir tiada.",
    src=["PAM:47-49"]),
 ]},
 ]}

terms = [
 ("radiation", T("辐射", "Radiation", "Sinaran"), T("以电磁波传递能量，不需要任何物质，例如阳光。", "Energy carried by electromagnetic waves, needing no material — sunlight, for example.", "Tenaga yang dibawa gelombang elektromagnet tanpa memerlukan bahan — contohnya cahaya matahari.")),
 ("shortwave", T("短波辐射", "Shortwave radiation", "Sinaran gelombang pendek"), T("太阳发出的辐射，集中在可见光附近。", "Radiation from the Sun, concentrated around visible light.", "Sinaran dari Matahari, tertumpu sekitar cahaya nampak.")),
 ("longwave", T("长波辐射", "Longwave radiation", "Sinaran gelombang panjang"), T("地面、空气和云发出的红外线。", "Infrared given off by the ground, the air and clouds.", "Inframerah yang dipancarkan oleh tanah, udara dan awan.")),
 ("direct-radiation", T("直接辐射", "Direct radiation", "Sinaran terus"), T("笔直从太阳照到地面的阳光。", "Sunlight reaching the ground in a straight line from the Sun.", "Cahaya matahari yang sampai ke tanah dalam garis lurus dari Matahari.")),
 ("diffuse-radiation", T("散射辐射", "Diffuse radiation", "Sinaran terserak"), T("被空气、尘埃和云散射后，从四面八方来的阳光。", "Sunlight scattered by air, dust and cloud, arriving from all directions.", "Cahaya matahari yang diserakkan oleh udara, debu dan awan, tiba dari semua arah.")),
 ("albedo", T("反照率", "Albedo", "Albedo"), T("表面反射掉的阳光比例；雪很高，森林很低。", "The share of sunlight a surface reflects; high for snow, low for forest.", "Bahagian cahaya matahari yang dipantulkan permukaan; tinggi bagi salji, rendah bagi hutan.")),
 ("energy-balance", T("能量平衡", "Energy balance", "Imbangan tenaga"), T("一年平均下来，地球收到和送走的能量相等。", "Over a year, the Earth sends away as much energy as it receives.", "Sepanjang tahun, Bumi menghantar keluar tenaga sebanyak yang diterimanya.")),
 ("latent-heat", T("潜热", "Latent heat", "Haba pendam"), T("蒸发水时“藏”进水汽的热，水汽凝结时再放出。", "Heat stored in water vapour by evaporation and released when it condenses.", "Haba yang tersimpan dalam wap air melalui penyejatan dan dilepaskan apabila ia terkondensasi.")),
 ("sensible-heat", T("感热", "Sensible heat", "Haba deria"), T("直接使空气升温、温度计量得到的热。", "Heat that directly warms the air and shows on a thermometer.", "Haba yang memanaskan udara secara terus dan kelihatan pada termometer.")),
 ("greenhouse-effect", T("温室效应", "Greenhouse effect", "Kesan rumah hijau"), T("水汽、二氧化碳等吸收地面红外线再送回地面，使地球保持温暖。", "Water vapour, CO₂ and other gases absorb the ground's infrared and send part back, keeping the Earth warm.", "Wap air, CO₂ dan gas lain menyerap inframerah tanah dan menghantar sebahagiannya kembali, memastikan Bumi kekal panas.")),
]

sources = [
 {"id": "NOAA-EOT", "short": "NOAA", "title": "General Solar Position Calculations (equation of time)", "publisher": "NOAA Global Monitoring Division", "url": "https://gml.noaa.gov/grad/solcalc/solareqns.PDF", "accessed": "2026-10-02"},
]

quiz = [
 {"stage": 2, "chapter": "ch03", "q": T("为什么北半球 1 月是冬天，虽然那时地球离太阳最近？", "Why is January winter in the Northern Hemisphere, though the Earth is then closest to the Sun?", "Mengapa Januari musim sejuk di Hemisfera Utara walaupun Bumi paling dekat dengan Matahari ketika itu?"),
  "options": [T("那时北半球偏离太阳，太阳低、白天短", "The north is tilted away: low Sun, short days", "Utara condong menjauhi Matahari: Matahari rendah, siang pendek"), T("太阳那时比较暗", "The Sun is dimmer then", "Matahari lebih malap ketika itu"), T("云特别多", "There is more cloud", "Lebih banyak awan"), T("海洋变冷", "The oceans cool", "Lautan menjadi sejuk")],
  "answer": 0, "why": T("季节来自地轴倾斜：太阳高度和白天长度的变化，比距离的变化重要得多。", "Seasons come from the tilted axis: changes in Sun height and day length matter far more than distance.", "Musim berpunca daripada paksi condong: perubahan ketinggian Matahari dan panjang siang jauh lebih penting daripada jarak.")},
 {"stage": 2, "chapter": "ch03", "q": T("下面哪种表面的反照率最低？", "Which surface has the lowest albedo?", "Permukaan manakah mempunyai albedo paling rendah?"),
  "options": [T("新雪", "Fresh snow", "Salji baharu"), T("厚云", "Thick cloud", "Awan tebal"), T("森林", "Forest", "Hutan"), T("沙地", "Sand", "Pasir")],
  "answer": 2, "why": T("森林颜色深、表面粗糙，只反射 3–10 % 的阳光。", "Forest is dark and rough and reflects only 3–10 % of sunlight.", "Hutan gelap dan kasar serta hanya memantulkan 3–10 % cahaya matahari.")},
 {"stage": 2, "chapter": "ch03", "q": T("为什么有云的晚上比晴朗的晚上暖？", "Why are cloudy nights warmer than clear ones?", "Mengapa malam berawan lebih panas daripada malam cerah?"),
  "options": [T("云会发光", "Clouds give off light", "Awan memancarkan cahaya"), T("云吸收地面的红外线，又发回地面", "Clouds absorb the ground's infrared and send it back", "Awan menyerap inframerah tanah dan menghantarnya kembali"), T("云里有热空气", "Clouds contain hot air", "Awan mengandungi udara panas"), T("云挡住了风", "Clouds stop the wind", "Awan menghalang angin")],
  "answer": 1, "why": T("云是很好的长波吸收体和发射体，像被子一样减少地面失热。", "Clouds absorb and emit longwave well, acting like a blanket on the ground's heat loss.", "Awan menyerap dan memancarkan gelombang panjang dengan baik, bertindak seperti selimut terhadap kehilangan haba tanah.")},
 {"stage": 2, "chapter": "ch03", "q": T("地面吸收的阳光，最大的一份拿去做什么？", "What takes the biggest share of the sunlight the surface absorbs?", "Apakah yang mengambil bahagian terbesar cahaya matahari yang diserap permukaan?"),
  "options": [T("蒸发水（潜热）", "Evaporating water (latent heat)", "Menyejatkan air (haba pendam)"), T("加热空气（感热）", "Heating the air (sensible heat)", "Memanaskan udara (haba deria)"), T("融化冰", "Melting ice", "Mencairkan ais"), T("被土壤储存", "Stored in the soil", "Disimpan dalam tanah")],
  "answer": 0, "why": T("51 份里有 23 份用来蒸发水。", "23 of the 51 units go into evaporating water.", "23 daripada 51 unit digunakan untuk menyejatkan air.")},
]

write_chapter(chapter, terms, sources, quiz)
