"""Chapter 6 — Condensation, fog and clouds."""
import sys
sys.path.insert(0, 'tools/content')
from build import T, P, L, N, write_chapter

chapter = {"id": "ch06", "num": 6, "stage": 3,
 "title": T("凝结、雾与云", "Condensation, fog and clouds", "Kondensasi, kabus dan awan"),
 "sources": ["PAM", "ESS"],
 "sections": [
 {"id": "s1", "heading": T("水汽变回水", "Vapour turns back into water", "Wap kembali menjadi air"), "level": "basic", "blocks": [
  P("{{t:condensation}}是蒸发的反过程：水汽变回液态的水。每一克水汽凝结，都会放出蒸发时“藏”起来的那份潜热，所以凝结会让周围的空气变暖。",
    "{{t:condensation}} is evaporation in reverse: water vapour turning back into liquid water. Every gram that condenses releases the latent heat that evaporation stored, so condensation warms the air around it.",
    "{{t:condensation}} ialah penyejatan secara terbalik: wap air bertukar kembali menjadi air cecair. Setiap gram yang terkondensasi membebaskan haba pendam yang disimpan semasa penyejatan, jadi kondensasi memanaskan udara di sekelilingnya.",
    defines=["condensation"], src=["PAM:75"]),
  P("大气里要发生凝结，需要三样东西：",
    "For condensation to happen in the atmosphere, three things are needed:",
    "Untuk kondensasi berlaku di atmosfera, tiga perkara diperlukan:",
    src=["PAM:75-76"]),
  L(("足够的水汽", "Enough water vapour", "Wap air yang mencukupi"),
    ("空气被冷却到露点或以下", "Air cooled to its dew point or below", "Udara disejukkan ke takat embun atau lebih rendah"),
    ("可以让水附着的微小颗粒", "Tiny particles for the water to collect on", "Zarah halus untuk air berkumpul"),
    src=["PAM:75-76"]),
  P("第三样就是{{t:condensation-nuclei}}：海盐、尘埃、烟和工业排放的微粒，直径只有约 0.1 到 1 微米。它们“喜欢水”，水汽会先凝结在它们上面。没有这些颗粒，空气就算过饱和也很难形成水滴。",
    "The third is {{t:condensation-nuclei}}: specks of sea salt, dust, smoke and industrial pollution about 0.1 to 1 micrometre across. They attract water, and vapour condenses on them first. Without them, droplets hardly form even in supersaturated air.",
    "Yang ketiga ialah {{t:condensation-nuclei}}: zarah garam laut, debu, asap dan pencemaran industri berukuran kira-kira 0.1 hingga 1 mikrometer. Ia menarik air, dan wap terkondensasi padanya dahulu. Tanpanya, titisan sukar terbentuk walaupun dalam udara lampau tepu.",
    defines=["condensation-nuclei"], src=["PAM:76", "ESS:97"]),
 ]},
 {"id": "s2", "heading": T("露、霾和雾", "Dew, haze and fog", "Embun, jerebu dan kabus"), "level": "basic", "blocks": [
  P("晴朗、无风的晚上，叶子、车顶这些东西以红外线失热，冷到露点以下，空气中的水汽就凝结在它们表面，这就是{{t:dew}}。露对作物是小小的额外水分，也会让叶面湿很久，利于病菌。",
    "On clear, calm nights, leaves, car roofs and the like lose heat as infrared and cool below the dew point; vapour then condenses on their surfaces as {{t:dew}}. For crops it is a little extra moisture — and it also keeps leaves wet for longer, which helps fungal disease.",
    "Pada malam cerah dan tenang, daun, bumbung kereta dan seumpamanya kehilangan haba sebagai inframerah dan menyejuk di bawah takat embun; wap kemudian terkondensasi di permukaannya sebagai {{t:dew}}. Bagi tanaman ia sedikit lembapan tambahan — dan ia juga memastikan daun basah lebih lama, yang membantu penyakit kulat.",
    defines=["dew"], src=["PAM:76-77", "ESS:97"]),
  P("当相对湿度升到约 75 % 时，水汽就开始凝结在凝结核上，颗粒变大但还很小，空气看起来朦朦胧胧、偏白，这叫{{t:haze}}。霾也可以只是尘埃、烟和盐粒，它们把各种颜色的光都散射掉，让天空从蓝变成乳白色。",
    "When relative humidity reaches about 75 %, vapour starts to collect on condensation nuclei; the particles grow but stay tiny, and the air looks milky and dim. This is {{t:haze}}. Haze can also be just dust, smoke and salt, which scatter all colours of light and turn the sky from blue to milky white.",
    "Apabila kelembapan relatif mencapai kira-kira 75 %, wap mula berkumpul pada nukleus kondensasi; zarah membesar tetapi kekal halus, dan udara kelihatan seperti susu dan malap. Inilah {{t:haze}}. Jerebu juga boleh terdiri daripada debu, asap dan garam sahaja, yang menyerakkan semua warna cahaya dan mengubah langit daripada biru kepada putih susu.",
    defines=["haze"], src=["ESS:97", "ESS:437", "PAM:78"]),
  P("如果水滴继续长大、变多，贴着地面的空气就成了一朵“躺在地上的云”，能见度降到 1 公里以下，这就是{{t:fog}}。晴朗无风的晚上地面冷却形成的雾叫辐射雾，日出后通常就散；暖湿空气流过冷的地面或海面形成的叫平流雾。",
    "If the droplets keep growing and multiplying, the air near the ground becomes a cloud lying on the surface and visibility falls below 1 km: {{t:fog}}. Fog formed by the ground cooling on clear, calm nights is radiation fog and usually clears after sunrise; fog formed when warm, moist air flows over cold land or sea is advection fog.",
    "Jika titisan terus membesar dan bertambah, udara berhampiran permukaan menjadi awan yang terletak di atas tanah dan keterlihatan jatuh di bawah 1 km: {{t:fog}}. Kabus yang terbentuk apabila tanah menyejuk pada malam cerah dan tenang ialah kabus sinaran dan biasanya hilang selepas matahari terbit; kabus yang terbentuk apabila udara panas lembap mengalir di atas tanah atau laut sejuk ialah kabus adveksi.",
    defines=["fog"], src=["ESS:97-98", "PAM:77"]),
  P("{{t:visibility}}就是能看多远。雾、霾、大雨都会降低能见度，影响开车、航空和航海。第 20 章会讲马来西亚的跨境烟霾。",
    "{{t:visibility}} is how far you can see. Fog, haze and heavy rain all reduce it, affecting roads, flights and shipping. Chapter 20 covers the transboundary haze that reaches Malaysia.",
    "{{t:visibility}} ialah sejauh mana anda boleh melihat. Kabus, jerebu dan hujan lebat semuanya mengurangkannya, menjejaskan jalan raya, penerbangan dan perkapalan. Bab 20 membincangkan jerebu rentas sempadan yang sampai ke Malaysia.",
    defines=["visibility"], src=["PAM:77-78"]),
 ]},
 {"id": "s3", "heading": T("云是什么", "What a cloud is", "Apa itu awan"), "level": "basic", "blocks": [
  P("{{t:cloud}}是悬浮在空中、看得见的一大群小水滴或冰晶，或者两者都有。一颗普通的云滴直径约 0.02 毫米，比头发还细得多，一点点上升气流就能托住它。",
    "A {{t:cloud}} is a visible mass of tiny water droplets or ice crystals — or both — floating in the air. An ordinary cloud droplet is about 0.02 mm across, far thinner than a hair, and the slightest rising air keeps it aloft.",
    "{{t:cloud}} ialah kumpulan titisan air atau hablur ais halus — atau kedua-duanya — yang kelihatan dan terapung di udara. Titisan awan biasa berukuran kira-kira 0.02 mm, jauh lebih halus daripada rambut, dan udara yang naik sedikit sahaja sudah cukup menampungnya.",
    defines=["cloud"], src=["PAM:78", "ESS:128"]),
  N("myth", "“乌云是一团水汽”——不对。水汽是看不见的气体。你看得见云，正是因为水汽已经凝结成了小水滴或冰晶。乌云看起来黑，是因为它又厚又密，阳光透不过来。",
    "‘A dark cloud is a mass of water vapour’ — no. Water vapour is an invisible gas. You can see a cloud precisely because the vapour has already condensed into droplets or ice. A dark cloud looks dark because it is thick and dense enough to block the sunlight.",
    "‘Awan gelap ialah gumpalan wap air’ — tidak. Wap air ialah gas yang tidak kelihatan. Anda boleh melihat awan kerana wap itu sudah terkondensasi menjadi titisan atau ais. Awan gelap kelihatan gelap kerana ia cukup tebal dan padat untuk menghalang cahaya matahari.",
    src=["ESS:435", "ESS:128"]),
  P("云为什么是白的？云滴虽小，但比空气分子大得多，它们把各种颜色的阳光都同样地往四面八方散射，加起来就是白色。云越厚越高，透过的光越少，底部就越灰暗。",
    "Why are clouds white? Droplets are tiny, but much bigger than air molecules, and they scatter all colours of sunlight equally in every direction — which adds up to white. The thicker and taller a cloud, the less light gets through and the greyer its base.",
    "Mengapa awan putih? Titisan itu halus, tetapi jauh lebih besar daripada molekul udara, dan ia menyerakkan semua warna cahaya matahari sama rata ke semua arah — yang bergabung menjadi putih. Semakin tebal dan tinggi awan, semakin kurang cahaya menembusinya dan semakin kelabu dasarnya.",
    src=["ESS:435"]),
 ]},
 {"id": "s4", "heading": T("十种云", "The ten cloud types", "Sepuluh jenis awan"), "level": "basic", "blocks": [
  P("世界气象组织按高度和样子把云分成十种，分属四组：{{t:high-cloud}}、{{t:middle-cloud}}、{{t:low-cloud}}，以及往上长的直展云。在热带，高云的云底约 6 到 18 公里，中云约 2 到 8 公里，低云从地面到约 2 公里。高云几乎全是冰晶。",
    "The World Meteorological Organization sorts clouds into ten types in four groups by height and appearance: {{t:high-cloud}}, {{t:middle-cloud}}, {{t:low-cloud}} and clouds that grow upward. In the tropics high-cloud bases are about 6–18 km up, middle clouds about 2–8 km, and low clouds from the surface to about 2 km. High clouds are almost entirely ice.",
    "Pertubuhan Meteorologi Sedunia mengelaskan awan kepada sepuluh jenis dalam empat kumpulan mengikut ketinggian dan rupa: {{t:high-cloud}}, {{t:middle-cloud}}, {{t:low-cloud}} dan awan yang tumbuh ke atas. Di kawasan tropika, dasar awan tinggi kira-kira 6–18 km, awan sederhana kira-kira 2–8 km, dan awan rendah dari permukaan hingga kira-kira 2 km. Awan tinggi hampir sepenuhnya ais.",
    defines=["high-cloud", "middle-cloud", "low-cloud"], src=["PAM:79-80", "ESS:103"]),
  {"type": "widget", "id": "W6"},
  P("云的底部离地面的高度叫{{t:cloud-base}}，云顶所在的高度叫{{t:cloud-top}}。积雨云的云底可能只有几百米，云顶却能冲到对流层顶。Windy 等天气 App 里都有“云底”和“云顶”图层。",
    "The height of a cloud's bottom above the ground is its {{t:cloud-base}}; the height of its top is its {{t:cloud-top}}. A cumulonimbus may have its base a few hundred metres up and its top at the tropopause. Apps such as Windy have ‘cloud base’ and ‘cloud tops’ layers.",
    "Ketinggian bahagian bawah awan dari tanah ialah {{t:cloud-base}}; ketinggian bahagian atasnya ialah {{t:cloud-top}}. Kumulonimbus mungkin mempunyai dasar beberapa ratus meter dan puncak di tropopaus. Aplikasi seperti Windy mempunyai lapisan ‘dasar awan’ dan ‘puncak awan’.",
    defines=["cloud-base", "cloud-top"], src=["ESS:108", "PAM:80"]),
  P("观测员用{{t:okta}}来报云量：把天空分成 8 份，0 是万里无云，8 是满天都是云。天气 App 里的“云量 %”是同一个意思。",
    "Observers report cloud cover in {{t:okta}}: the sky is divided into eighths, 0 meaning cloudless and 8 completely overcast. The ‘cloud cover %’ in a weather app means the same thing.",
    "Pencerap melaporkan litupan awan dalam {{t:okta}}: langit dibahagikan kepada lapan bahagian, 0 bermaksud tiada awan dan 8 mendung sepenuhnya. ‘Litupan awan %’ dalam aplikasi cuaca bermaksud perkara yang sama.",
    defines=["okta"], src=["PAM:80"]),
 ]},
 {"id": "s5", "heading": T("云还有哪些名字", "More cloud names", "Lebih banyak nama awan"), "level": "advanced", "blocks": [
  {"type": "keyval", "src": ["ESS:107-110"], "rows": [
   {"k": T("fractus 碎", "fractus", "fractus"), "v": T("破碎、边缘参差的层云或积云", "Ragged, torn stratus or cumulus", "Stratus atau kumulus yang koyak dan tidak rata")},
   {"k": T("humilis 淡", "humilis", "humilis"), "v": T("只长一点点的扁平积云：晴天积云", "Flat cumulus with little growth: fair-weather cumulus", "Kumulus rata yang tumbuh sedikit: kumulus cuaca baik")},
   {"k": T("congestus 浓", "congestus", "congestus"), "v": T("长得很高、像花椰菜的积云，下阵雨", "Tall, cauliflower-like cumulus that gives showers", "Kumulus tinggi seperti kubis bunga yang membawa hujan lebat sekejap")},
   {"k": T("mammatus 乳状", "mammatus", "mammatus"), "v": T("挂在云底的一个个袋状突起，常在雷雨云下面", "Pouch-like bulges hanging from a cloud base, often under a thunderstorm", "Bonjolan seperti kantung yang tergantung di dasar awan, sering di bawah ribut petir")},
   {"k": T("pileus 幞状", "pileus", "pileus"), "v": T("盖在正在长高的积云顶上的一顶“帽子”", "A ‘cap’ on top of a growing cumulus", "‘Topi’ di atas kumulus yang sedang tumbuh")},
   {"k": T("lenticularis 荚状", "lenticularis", "lenticularis"), "v": T("山后气流形成的透镜状云", "Lens-shaped cloud formed in waves of air downwind of mountains", "Awan berbentuk kanta yang terbentuk dalam gelombang udara di belakang gunung")}]},
 ]},
 ]}

terms = [
 ("condensation", T("凝结", "Condensation", "Kondensasi"), T("水汽变回液态水，同时放出潜热。", "Water vapour turning back into liquid water, releasing latent heat.", "Wap air bertukar kembali menjadi air cecair, membebaskan haba pendam.")),
 ("condensation-nuclei", T("凝结核", "Condensation nuclei", "Nukleus kondensasi"), T("海盐、尘埃、烟等微粒，水汽先凝结在它们上面。", "Specks of salt, dust or smoke on which vapour condenses first.", "Zarah garam, debu atau asap tempat wap terkondensasi dahulu.")),
 ("dew", T("露", "Dew", "Embun"), T("晴朗无风的晚上，水汽在冷却的表面上凝结成的水珠。", "Water condensed on surfaces that have cooled on clear, calm nights.", "Air yang terkondensasi pada permukaan yang menyejuk pada malam cerah dan tenang.")),
 ("haze", T("霾", "Haze", "Jerebu"), T("微小颗粒（尘、烟、盐，或带水的凝结核）使空气发白、能见度降低。", "Tiny particles (dust, smoke, salt or damp nuclei) making the air milky and cutting visibility.", "Zarah halus (debu, asap, garam atau nukleus lembap) yang menjadikan udara seperti susu dan mengurangkan keterlihatan.")),
 ("fog", T("雾", "Fog", "Kabus"), T("贴地的云，能见度低于 1 公里。", "A cloud at ground level, with visibility under 1 km.", "Awan di paras tanah, dengan keterlihatan kurang daripada 1 km.")),
 ("visibility", T("能见度", "Visibility", "Keterlihatan"), T("在地面上能看多远。", "How far you can see at ground level.", "Sejauh mana anda boleh melihat di paras tanah.")),
 ("cloud", T("云", "Cloud", "Awan"), T("悬浮在空中的大群小水滴或冰晶。", "A visible mass of tiny droplets or ice crystals floating in the air.", "Kumpulan titisan halus atau hablur ais yang terapung di udara.")),
 ("high-cloud", T("高云", "High cloud", "Awan tinggi"), T("卷云、卷层云、卷积云；热带云底约 6–18 公里，几乎全是冰晶。", "Cirrus, cirrostratus, cirrocumulus; in the tropics based about 6–18 km up, nearly all ice.", "Sirus, sirostratus, sirokumulus; di kawasan tropika berdasar kira-kira 6–18 km, hampir semuanya ais.")),
 ("middle-cloud", T("中云", "Middle cloud", "Awan sederhana"), T("高层云、高积云；热带云底约 2–8 公里。", "Altostratus and altocumulus; in the tropics based about 2–8 km up.", "Altostratus dan altokumulus; di kawasan tropika berdasar kira-kira 2–8 km.")),
 ("low-cloud", T("低云", "Low cloud", "Awan rendah"), T("层云、层积云、雨层云；云底在约 2 公里以下。", "Stratus, stratocumulus, nimbostratus; based below about 2 km.", "Stratus, stratokumulus, nimbostratus; berdasar di bawah kira-kira 2 km.")),
 ("cloud-base", T("云底", "Cloud base", "Dasar awan"), T("云的底部离地面的高度。", "The height of a cloud's bottom above the ground.", "Ketinggian bahagian bawah awan dari tanah.")),
 ("cloud-top", T("云顶", "Cloud top", "Puncak awan"), T("云的顶部所在的高度。", "The height of a cloud's top.", "Ketinggian bahagian atas awan.")),
 ("okta", T("八分量（okta）", "Okta", "Okta"), T("云量单位：天空分 8 份，0 无云，8 满天云。", "Unit of cloud cover: the sky in eighths, 0 clear to 8 overcast.", "Unit litupan awan: langit dalam perlapanan, 0 cerah hingga 8 mendung.")),
]

quiz = [
 {"stage": 3, "chapter": "ch06", "q": T("为什么看得见云，却看不见水汽？", "Why can you see a cloud but not water vapour?", "Mengapa anda boleh melihat awan tetapi tidak wap air?"),
  "options": [T("云是水汽加了颜色", "A cloud is coloured vapour", "Awan ialah wap berwarna"), T("云里的水汽已经凝结成小水滴或冰晶", "In a cloud the vapour has condensed into droplets or ice", "Dalam awan, wap sudah terkondensasi menjadi titisan atau ais"), T("云离我们比较近", "Clouds are closer to us", "Awan lebih dekat dengan kita"), T("云是烟", "Clouds are smoke", "Awan ialah asap")],
  "answer": 1, "why": T("水汽是透明的气体；云是凝结出来的水滴和冰晶。", "Vapour is a transparent gas; clouds are the droplets and ice it condenses into.", "Wap ialah gas lutsinar; awan ialah titisan dan ais hasil kondensasinya.")},
 {"stage": 3, "chapter": "ch06", "q": T("哪一种云最可能带来雷电和暴雨？", "Which cloud is most likely to bring lightning and a downpour?", "Awan manakah paling mungkin membawa kilat dan hujan lebat?"),
  "options": [T("卷云", "Cirrus", "Sirus"), T("层云", "Stratus", "Stratus"), T("积雨云", "Cumulonimbus", "Kumulonimbus"), T("高积云", "Altocumulus", "Altokumulus")],
  "answer": 2, "why": T("积雨云可以长到对流层顶，有强烈的上下气流，带来雷电、暴雨和强风。", "Cumulonimbus grows to the tropopause with violent up- and downdraughts: lightning, downpours and gusts.", "Kumulonimbus tumbuh hingga tropopaus dengan arus naik dan turun yang kuat: kilat, hujan lebat dan angin kencang.")},
 {"stage": 3, "chapter": "ch06", "q": T("云量报“8 okta”是什么意思？", "What does a cloud cover of ‘8 oktas’ mean?", "Apakah maksud litupan awan ‘8 okta’?"),
  "options": [T("万里无云", "Cloudless", "Tiada awan"), T("一半天空有云", "Half the sky covered", "Separuh langit berawan"), T("满天都是云", "Completely overcast", "Mendung sepenuhnya"), T("云底 8 公里", "Cloud base at 8 km", "Dasar awan pada 8 km")],
  "answer": 2, "why": T("天空分成 8 份，8 份都有云就是满天云。", "The sky is split into eighths; all eight covered means overcast.", "Langit dibahagi lapan; kesemua lapan dilitupi bermaksud mendung.")},
]

write_chapter(chapter, terms, [], quiz)
