"""Chapter 14 — ENSO, the MJO and the IOD."""
import sys
sys.path.insert(0, 'tools/content')
from build import T, P, L, N, write_chapter

chapter = {"id": "ch14", "num": 14, "stage": 5,
 "title": T("厄尔尼诺、MJO 与印度洋偶极子", "El Niño, the MJO and the Indian Ocean Dipole", "El Niño, MJO dan Dipol Lautan Hindi"),
 "sources": ["ESS", "FUN", "NOAA-CPC-RONI", "MET-PHEN", "METMY-SWM2024", "CLIMGOV-MJO", "CLIMGOV-IOD"],
 "sections": [
 {"id": "s1", "heading": T("厄尔尼诺和拉尼娜", "El Niño and La Niña", "El Niño dan La Niña"), "level": "basic", "blocks": [
  P("第 11 章讲过 Walker 环流：平常信风把暖水推到西太平洋，东南亚这边空气上升、多雨。每隔几年，信风会变弱，甚至改吹西风，暖水就往东流到南美洲那边，东太平洋赤道一带的海水比平常暖很多。这叫{{t:el-nino}}。",
    "Chapter 11 described the Walker circulation: normally the trade winds push warm water to the western Pacific, and air rises with plenty of rain on South-East Asia's side. Every few years the trades weaken, or even turn westerly, and the warm water flows east towards South America, leaving the eastern equatorial Pacific much warmer than usual. This is {{t:el-nino}}.",
    "Bab 11 menerangkan peredaran Walker: biasanya angin pasat menolak air panas ke Pasifik barat, dan udara naik dengan banyak hujan di sebelah Asia Tenggara. Setiap beberapa tahun angin pasat melemah, malah bertukar menjadi angin barat, dan air panas mengalir ke timur ke arah Amerika Selatan, menjadikan Pasifik khatulistiwa timur jauh lebih panas daripada biasa. Inilah {{t:el-nino}}.",
    defines=["el-nino"], src=["ESS:205-206"]),
  P("同时，太平洋两端的气压也像跷跷板一样互换：西边气压升高，东边气压降低。这个跷跷板叫{{t:southern-oscillation}}。海水变暖和气压互换差不多同时发生，所以两者合称{{t:enso}}。",
    "At the same time the pressure at the two ends of the Pacific swaps like a seesaw: it rises in the west and falls in the east. The seesaw is the {{t:southern-oscillation}}. Because the ocean warming and the pressure swap happen together, the two are called by one name: {{t:enso}}.",
    "Pada masa yang sama tekanan di kedua-dua hujung Pasifik bertukar seperti jongkang-jongkit: naik di barat dan turun di timur. Jongkang-jongkit ini ialah {{t:southern-oscillation}}. Oleh sebab pemanasan laut dan pertukaran tekanan berlaku bersama, kedua-duanya dipanggil dengan satu nama: {{t:enso}}.",
    defines=["southern-oscillation", "enso"], src=["ESS:206"]),
  P("相反的情况叫{{t:la-nina}}：信风特别强，东太平洋和中太平洋的海水比平常冷，暖水和多雨的天气更集中在西太平洋。",
    "The opposite is {{t:la-nina}}: the trades are unusually strong, the central and eastern Pacific are colder than normal, and the warm water and rainy weather are crowded into the western Pacific.",
    "Keadaan bertentangan ialah {{t:la-nina}}: angin pasat luar biasa kuat, Pasifik tengah dan timur lebih sejuk daripada biasa, dan air panas serta cuaca hujan tertumpu di Pasifik barat.",
    defines=["la-nina"], src=["ESS:207"]),
  {"type": "widget", "id": "W12"},
  {"type": "map", "id": "M6"},
  N("key", "每一次 ENSO 都不完全一样，强弱和过程各有不同。所以“今年是厄尔尼诺”只是告诉你偏向哪一边，不等于每一天都会干。",
    "Each ENSO event is different in strength and behaviour. So ‘this is an El Niño year’ tells you which way the odds lean; it does not mean every day will be dry.",
    "Setiap peristiwa ENSO berbeza dari segi kekuatan dan perjalanannya. Jadi ‘tahun ini El Niño’ memberitahu ke arah mana kebarangkalian condong; ia tidak bermakna setiap hari akan kering.",
    src=["ESS:206"]),
 ]},
 {"id": "s2", "heading": T("怎样知道现在是不是厄尔尼诺", "How to tell whether El Niño is under way", "Cara mengetahui sama ada El Niño sedang berlaku"), "level": "basic", "blocks": [
  P("美国 NOAA 气候预测中心（CPC）用一个数字来判断，自 2026 年 2 月起改用{{t:roni}}。做法是：取赤道太平洋 Niño 3.4 区（5°N–5°S、120°–170°W）三个月的平均海温距平，再减去整个热带（20°N–20°S）的平均距平。减掉热带平均，是为了不把全球变暖造成的整体升温误当成厄尔尼诺。",
    "The US NOAA Climate Prediction Center (CPC) decides with a single number, and since February 2026 that number is the {{t:roni}}. It takes the three-month average sea-temperature departure in the Niño 3.4 box of the equatorial Pacific (5°N–5°S, 120°–170°W) and subtracts the average departure across the whole tropics (20°N–20°S). Subtracting the tropical average stops the overall warming of the oceans being mistaken for El Niño.",
    "Pusat Ramalan Iklim NOAA AS (CPC) membuat keputusan dengan satu nombor, dan sejak Februari 2026 nombor itu ialah {{t:roni}}. Ia mengambil purata tiga bulan sisihan suhu laut di kotak Niño 3.4 Pasifik khatulistiwa (5°U–5°S, 120°–170°B) dan menolak purata sisihan seluruh kawasan tropika (20°U–20°S). Penolakan purata tropika mengelakkan pemanasan keseluruhan lautan disangka El Niño.",
    defines=["roni"], src=["NOAA-CPC-RONI"]),
  L(("+0.5 °C 或以上：厄尔尼诺的状态", "+0.5 °C or more: El Niño conditions", "+0.5 °C atau lebih: keadaan El Niño"),
    ("−0.5 °C 或以下：拉尼娜的状态", "−0.5 °C or less: La Niña conditions", "−0.5 °C atau kurang: keadaan La Niña"),
    ("要连续至少 5 个重叠的三个月都超过门槛，才算一次厄尔尼诺或拉尼娜", "It counts as an El Niño or La Niña episode only when at least 5 overlapping three-month seasons in a row pass the threshold", "Ia dikira sebagai episod El Niño atau La Niña hanya apabila sekurang-kurangnya 5 musim tiga bulan bertindih berturut-turut melepasi ambang"),
    src=["NOAA-CPC-RONI"]),
  {"type": "chart", "src": ["NOAA-CPC-RONI"], "chart": {"kind": "line", "series_file": "roni",
    "title": T("RONI 指数，1980–2026", "The RONI, 1980–2026", "Indeks RONI, 1980–2026"),
    "x": {"col": "season", "label": T("年份", "Year", "Tahun"), "format": "year"},
    "y": {"label": T("距平", "Departure", "Sisihan"), "unit": "°C",
          "refs": [{"v": 0.5, "label": T("厄尔尼诺门槛", "El Niño threshold", "Ambang El Niño")},
                   {"v": -0.5, "label": T("拉尼娜门槛", "La Niña threshold", "Ambang La Niña")}]},
    "series": [{"col": "anomaly", "name": T("RONI", "RONI", "RONI"), "color": "sky"}]}},
  P("图上最高的两座峰是 1997–98 年和 2015–16 年的强厄尔尼诺（RONI 超过 +2 °C），最深的谷之一是 2010–11 年的拉尼娜（约 −1.6 °C）。拖动图表就能读出每一季的数值。最新一季 2026 年 6–8 月是 +1.36 °C，已经连续两季超过 +0.5 °C。",
    "The two highest peaks are the strong El Niños of 1997–98 and 2015–16 (RONI above +2 °C); one of the deepest troughs is the La Niña of 2010–11 (about −1.6 °C). Drag across the chart to read each season. The latest season, June–August 2026, is +1.36 °C, the second season in a row above +0.5 °C.",
    "Dua puncak tertinggi ialah El Niño kuat 1997–98 dan 2015–16 (RONI melebihi +2 °C); salah satu lembah terdalam ialah La Niña 2010–11 (kira-kira −1.6 °C). Seret merentasi carta untuk membaca setiap musim. Musim terkini, Jun–Ogos 2026, ialah +1.36 °C, musim kedua berturut-turut melebihi +0.5 °C.",
    src=["NOAA-CPC-RONI"]),
  {"type": "dataset", "id": "noaa-roni"},
  N("tip", "很多旧文章和网站还在用 ONI，就是不减热带平均的旧版本。两个数字可以差不少：2026 年 6–8 月，ONI 是 +1.80 °C，RONI 是 +1.36 °C。看到两个数字不同，先看它用的是哪一个指数。",
    "Many older articles and websites still quote the ONI, the older version that does not subtract the tropical average. The two can differ a good deal: for June–August 2026 the ONI was +1.80 °C and the RONI +1.36 °C. When two numbers disagree, check which index each one uses.",
    "Banyak artikel dan laman web lama masih memetik ONI, versi lama yang tidak menolak purata tropika. Kedua-duanya boleh berbeza agak banyak: bagi Jun–Ogos 2026 ONI ialah +1.80 °C dan RONI +1.36 °C. Apabila dua nombor tidak sama, semak indeks mana yang digunakan.",
    src=["NOAA-CPC-RONI"]),
 ]},
 {"id": "s3", "heading": T("远方的海洋怎样影响马来西亚", "How a distant ocean reaches Malaysia", "Bagaimana lautan jauh mempengaruhi Malaysia"), "level": "basic", "blocks": [
  P("一片海洋变暖或变冷，可以改变很远地方的天气，这叫{{t:teleconnection}}。强厄尔尼诺时，印尼、澳洲和非洲南部常常干旱，秘鲁和厄瓜多尔却常有大雨和水灾。",
    "When one part of the ocean turns warmer or colder it can change the weather far away: a {{t:teleconnection}}. During strong El Niños, drought is common in Indonesia, Australia and southern Africa, while Peru and Ecuador often get heavy rain and floods.",
    "Apabila sebahagian lautan menjadi lebih panas atau sejuk, ia boleh mengubah cuaca di tempat yang jauh: {{t:teleconnection}}. Semasa El Niño kuat, kemarau biasa berlaku di Indonesia, Australia dan selatan Afrika, manakala Peru dan Ecuador sering menerima hujan lebat dan banjir.",
    defines=["teleconnection"], src=["ESS:206-207"]),
  {"type": "table", "src": ["MET-PHEN", "FUN:175"],
   "caption": T("ENSO 对马来西亚雨量的影响", "What ENSO does to Malaysia's rainfall", "Kesan ENSO terhadap hujan Malaysia"),
   "headers": [T("情况", "State", "Keadaan"), T("影响", "Effect", "Kesan")],
   "rows": [[T("中等或强的厄尔尼诺", "Moderate or strong El Niño", "El Niño sederhana atau kuat"), T("沙巴、砂拉越在西南季风（6–8 月）和东北季风（11–2 月）雨量远低于平均；半岛只在西南季风（6–8 月）偏少", "Sabah and Sarawak get far below-average rain in both the south-west monsoon (June–August) and the north-east monsoon (November–February); the Peninsula is drier only in the south-west monsoon (June–August)", "Sabah dan Sarawak menerima hujan jauh di bawah purata dalam monsun barat daya (Jun–Ogos) dan monsun timur laut (November–Februari); Semenanjung lebih kering hanya dalam monsun barat daya (Jun–Ogos)")],
            [T("弱的厄尔尼诺", "Weak El Niño", "El Niño lemah"), T("影响很小", "Little effect", "Kesan kecil")],
            [T("拉尼娜", "La Niña", "La Niña"), T("西太平洋赤道一带气压降低，云多、雨大；马来西亚、菲律宾和印尼常有大雨", "Pressure falls over the western equatorial Pacific, with more cloud and rain; Malaysia, the Philippines and Indonesia often get heavy rain", "Tekanan turun di Pasifik khatulistiwa barat, dengan lebih banyak awan dan hujan; Malaysia, Filipina dan Indonesia sering menerima hujan lebat")]]},
  N("key", "马来西亚 2024 年的西南季风期间，ENSO 是中性的。大马气象局的检讨报告说，这时远方的影响很小，天气比较接近长期平均。",
    "During Malaysia's 2024 south-west monsoon ENSO was neutral. MetMalaysia's review says that with no distant push, the weather stayed closer to the long-term average.",
    "Semasa monsun barat daya 2024 di Malaysia, ENSO berada dalam keadaan neutral. Kajian semula MetMalaysia menyatakan bahawa tanpa pengaruh jauh, cuaca kekal lebih hampir kepada purata jangka panjang.",
    src=["METMY-SWM2024"]),
 ]},
 {"id": "s4", "heading": T("MJO：往东走的雨带", "The MJO: a band of rain that travels east", "MJO: jalur hujan yang bergerak ke timur"), "level": "basic", "blocks": [
  P("ENSO 一次要一两年，但热带还有一个快得多的变化：{{t:mjo}}。它是一大片云多雨多的区域，从印度洋出发，以每秒约 4 到 8 米的速度向东移动，经过东南亚，再到太平洋。大约 30 到 60 天绕地球一圈。雨带后面跟着一段云少雨少的日子。",
    "ENSO takes a year or two, but the tropics also have a much faster swing: the {{t:mjo}}. It is a huge area of extra cloud and rain that sets off from the Indian Ocean and moves east at about 4 to 8 metres a second, across South-East Asia and on into the Pacific, circling the globe in roughly 30 to 60 days. Behind the wet band come drier days with fewer storms.",
    "ENSO mengambil masa setahun dua, tetapi kawasan tropika juga mempunyai ayunan yang jauh lebih cepat: {{t:mjo}}. Ia ialah kawasan besar yang lebih berawan dan berhujan, bermula dari Lautan Hindi dan bergerak ke timur kira-kira 4 hingga 8 meter sesaat, merentasi Asia Tenggara dan terus ke Pasifik, mengelilingi bumi dalam kira-kira 30 hingga 60 hari. Di belakang jalur basah datang hari-hari lebih kering dengan kurang ribut.",
    defines=["mjo"], src=["FUN:175", "CLIMGOV-MJO"]),
  {"type": "map", "id": "M7"},
  P("预报员把 MJO 分成 8 个相位，第 4、5 相位时雨带在海洋性大陆（马来西亚、印尼一带）上空。大马气象局的报告指出：2024 年 5 月 MJO 在第 5 相位活跃，9 月上中旬在第 4、5 相位活跃，都可能加强了这一带的对流和大雨；6 到 8 月 MJO 很弱，对雨量的影响很小。",
    "Forecasters divide the MJO into 8 phases; in phases 4 and 5 the wet band sits over the Maritime Continent — Malaysia and Indonesia. MetMalaysia's review notes that an active MJO in phase 5 in May 2024, and in phases 4 and 5 in early to mid-September 2024, likely enhanced convection and heavy rain over the region, while from June to August the MJO was weak and did little to the rainfall.",
    "Peramal membahagikan MJO kepada 8 fasa; dalam fasa 4 dan 5 jalur basah berada di atas Benua Maritim — Malaysia dan Indonesia. Kajian semula MetMalaysia mencatat bahawa MJO aktif dalam fasa 5 pada Mei 2024, dan dalam fasa 4 dan 5 pada awal hingga pertengahan September 2024, berkemungkinan menguatkan perolakan dan hujan lebat di rantau ini, manakala dari Jun hingga Ogos MJO lemah dan tidak banyak mempengaruhi hujan.",
    src=["METMY-SWM2024"]),
  {"type": "dataset", "id": "bom-rmm"},
 ]},
 {"id": "s5", "heading": T("印度洋偶极子", "The Indian Ocean Dipole", "Dipol Lautan Hindi"), "level": "basic", "blocks": [
  P("印度洋也有类似的跷跷板，叫{{t:iod}}。正相位时，东印度洋（苏门答腊、爪哇附近）海水偏冷，西印度洋偏暖，印尼和澳洲比较干，东非比较湿；负相位刚好相反。它通常在 9 到 11 月最明显。",
    "The Indian Ocean has a seesaw of its own: the {{t:iod}}. In its positive phase the eastern Indian Ocean, near Sumatra and Java, is cooler than usual and the western side warmer; Indonesia and Australia tend to be drier and East Africa wetter. The negative phase is the reverse. It is usually strongest from September to November.",
    "Lautan Hindi mempunyai jongkang-jongkitnya sendiri: {{t:iod}}. Dalam fasa positif, Lautan Hindi timur berhampiran Sumatera dan Jawa lebih sejuk daripada biasa dan bahagian barat lebih panas; Indonesia dan Australia cenderung lebih kering dan Afrika Timur lebih basah. Fasa negatif adalah sebaliknya. Ia biasanya paling kuat dari September hingga November.",
    defines=["iod"], src=["CLIMGOV-IOD"]),
  {"type": "map", "id": "M8"},
  N("tip", "看季节预报时，可以同时留意三件事：ENSO（太平洋）、IOD（印度洋）、MJO（未来几个星期）。前两个影响几个月，MJO 影响几个星期。",
    "When you read a seasonal outlook, keep an eye on three things: ENSO (the Pacific), the IOD (the Indian Ocean) and the MJO (the next few weeks). The first two act over months; the MJO over weeks.",
    "Apabila membaca tinjauan bermusim, perhatikan tiga perkara: ENSO (Pasifik), IOD (Lautan Hindi) dan MJO (beberapa minggu akan datang). Dua yang pertama bertindak dalam beberapa bulan; MJO dalam beberapa minggu.",
    src=["CLIMGOV-IOD", "FUN:175"]),
 ]},
 ]}

terms = [
 ("el-nino", T("厄尔尼诺", "El Niño", "El Niño"), T("东太平洋赤道一带海水比平常暖很多的现象；东南亚常偏干。", "Unusual warming of the eastern equatorial Pacific; South-East Asia is often drier.", "Pemanasan luar biasa Pasifik khatulistiwa timur; Asia Tenggara sering lebih kering.")),
 ("southern-oscillation", T("南方涛动", "Southern Oscillation", "Ayunan Selatan"), T("太平洋东西两端气压像跷跷板一样互换。", "The seesaw of surface pressure between the two ends of the Pacific.", "Jongkang-jongkit tekanan permukaan antara dua hujung Pasifik.")),
 ("enso", T("ENSO", "ENSO", "ENSO"), T("厄尔尼诺和南方涛动的合称；包括厄尔尼诺、正常和拉尼娜。", "El Niño and the Southern Oscillation together, covering El Niño, neutral and La Niña.", "El Niño dan Ayunan Selatan bersama, merangkumi El Niño, neutral dan La Niña.")),
 ("la-nina", T("拉尼娜", "La Niña", "La Niña"), T("中、东太平洋海水比平常冷，信风特别强；马来西亚常偏湿。", "Colder than normal central and eastern Pacific with strong trades; Malaysia is often wetter.", "Pasifik tengah dan timur lebih sejuk dengan angin pasat kuat; Malaysia sering lebih basah.")),
 ("roni", T("RONI 指数", "RONI", "RONI"), T("NOAA 判断 ENSO 的指数：Niño 3.4 区海温距平减去热带平均；±0.5 °C 为门槛。", "NOAA's ENSO index: the Niño 3.4 sea-temperature departure minus the tropical average; ±0.5 °C is the threshold.", "Indeks ENSO NOAA: sisihan suhu laut Niño 3.4 tolak purata tropika; ambangnya ±0.5 °C.")),
 ("teleconnection", T("遥相关", "Teleconnection", "Telesambungan"), T("一片海洋的冷暖改变很远地方天气的联系。", "A link by which a warm or cool ocean changes the weather far away.", "Hubungan apabila lautan panas atau sejuk mengubah cuaca di tempat jauh.")),
 ("mjo", T("MJO（马登–朱利安振荡）", "MJO (Madden–Julian Oscillation)", "MJO (Ayunan Madden–Julian)"), T("向东移动的热带云雨带，约 30–60 天绕地球一圈；分 8 个相位。", "An eastward-moving tropical band of cloud and rain that circles the globe in about 30–60 days; described in 8 phases.", "Jalur awan dan hujan tropika yang bergerak ke timur, mengelilingi bumi dalam kira-kira 30–60 hari; diterangkan dalam 8 fasa.")),
 ("iod", T("印度洋偶极子（IOD）", "Indian Ocean Dipole (IOD)", "Dipol Lautan Hindi (IOD)"), T("印度洋东西两边海温的跷跷板；正相位时印尼一带偏干。", "A seesaw of sea temperature between the east and west Indian Ocean; positive phases dry Indonesia.", "Jongkang-jongkit suhu laut antara Lautan Hindi timur dan barat; fasa positif mengeringkan Indonesia.")),
]

sources = [
 {"id": "FUN", "short": "Fundamentals of Meteorology", "title": "Fundamentals of Meteorology", "publisher": "dokumen.pub edition", "url": "", "accessed": ""},
 {"id": "NOAA-CPC-RONI", "short": "NOAA CPC", "title": "Relative Oceanic Niño Index (RONI) — announcement and data", "publisher": "NOAA Climate Prediction Center", "url": "https://www.cpc.ncep.noaa.gov/products/analysis_monitoring/enso/roni/", "accessed": "2026-10-02"},
 {"id": "CLIMGOV-MJO", "short": "Climate.gov", "title": "What is the MJO, and why do we care?", "publisher": "NOAA Climate.gov", "url": "https://www.climate.gov/news-features/blogs/enso/what-mjo-and-why-do-we-care", "accessed": "2026-10-02"},
 {"id": "CLIMGOV-IOD", "short": "Climate.gov", "title": "Meet ENSO's neighbor, the Indian Ocean Dipole", "publisher": "NOAA Climate.gov", "url": "https://www.climate.gov/news-features/blogs/enso/meet-enso%E2%80%99s-neighbor-indian-ocean-dipole", "accessed": "2026-10-02"},
]

datasets = [
 {"id": "noaa-roni", "name": "RONI (Relative Oceanic Niño Index)", "provider": "NOAA Climate Prediction Center",
  "what": T("每个重叠三个月季节一个数值，从 1950 年开始；本章的 RONI 图就是用它画的。", "One value for each overlapping three-month season since 1950. This chapter's RONI chart is drawn from it.", "Satu nilai bagi setiap musim tiga bulan bertindih sejak 1950. Carta RONI bab ini dilukis daripadanya."),
  "resolution": T("一个区域平均值", "One area average", "Satu purata kawasan"), "update": T("每月", "Monthly", "Bulanan"), "format": "Text (ASCII)",
  "licence": {"text": "US Government work", "url": "https://www.cpc.ncep.noaa.gov/products/analysis_monitoring/enso/roni/"},
  "params": [{"raw": "SEAS", "meaning": T("三个月季节，例如 JJA = 6、7、8 月", "Three-month season, e.g. JJA = June, July, August", "Musim tiga bulan, contohnya JJA = Jun, Julai, Ogos"), "unit": "—", "chapter": 14},
             {"raw": "YR", "meaning": T("年份", "Year", "Tahun"), "unit": "—", "chapter": 14},
             {"raw": "ANOM", "meaning": T("相对距平：Niño 3.4 区减去热带平均", "Relative departure: Niño 3.4 minus the tropical average", "Sisihan relatif: Niño 3.4 tolak purata tropika"), "unit": "°C", "chapter": 14}],
  "sample": {"columns": ["SEAS", "YR", "ANOM"], "rows": [["AMJ", "2026", "0.49"], ["MJJ", "2026", "0.97"], ["JJA", "2026", "1.36"]], "source": "RONI.ascii.txt", "fetched": "2026-10-02"},
  "links": [
   {"level": "view", "label": T("RONI 说明页", "RONI page", "Halaman RONI"), "url": "https://www.cpc.ncep.noaa.gov/products/analysis_monitoring/enso/roni/"},
   {"level": "try", "label": T("直接打开数据（纯文本）", "Open the data (plain text)", "Buka data (teks biasa)"), "url": "https://www.cpc.ncep.noaa.gov/data/indices/RONI.ascii.txt"},
   {"level": "pro", "label": T("CPC 每月 ENSO 诊断讨论", "CPC monthly ENSO diagnostic discussion", "Perbincangan diagnostik ENSO bulanan CPC"), "url": "https://www.cpc.ncep.noaa.gov/products/analysis_monitoring/enso_advisory/ensodisc.shtml"}]},
 {"id": "bom-rmm", "name": "RMM MJO index", "provider": "Australian Bureau of Meteorology",
  "what": T("每天一行：两个 RMM 数值、MJO 相位（1–8）和强度。强度小于 1 表示 MJO 很弱。", "One row a day: the two RMM values, the MJO phase (1–8) and its amplitude. An amplitude below 1 means the MJO is weak.", "Satu baris sehari: dua nilai RMM, fasa MJO (1–8) dan amplitudnya. Amplitud di bawah 1 bermakna MJO lemah."),
  "resolution": T("全球一个指数", "One global index", "Satu indeks global"), "update": T("这个文件的最后一行是 2024 年 2 月 24 日", "This file's last row is 24 February 2024", "Baris terakhir fail ini ialah 24 Februari 2024"), "format": "Text (ASCII)",
  "licence": {"text": "© Commonwealth of Australia (Bureau of Meteorology)", "url": "https://www.bom.gov.au/climate/mjo/"},
  "params": [{"raw": "RMM1, RMM2", "meaning": T("MJO 图上的横轴和纵轴", "The two axes of the MJO diagram", "Dua paksi gambar rajah MJO"), "unit": "—", "chapter": 14},
             {"raw": "phase", "meaning": T("相位 1–8；4、5 在海洋性大陆", "Phase 1–8; 4 and 5 are over the Maritime Continent", "Fasa 1–8; 4 dan 5 di atas Benua Maritim"), "unit": "—", "chapter": 14},
             {"raw": "amplitude", "meaning": T("强度；1 以上为活跃", "Strength; above 1 is active", "Kekuatan; melebihi 1 adalah aktif"), "unit": "—", "chapter": 14}],
  "sample": {"columns": ["year", "month", "day", "RMM1", "RMM2", "phase", "amplitude"], "rows": [["2024", "2", "22", "0.236", "0.249", "6", "0.343"], ["2024", "2", "23", "0.202", "0.325", "6", "0.383"], ["2024", "2", "24", "-0.003", "0.128", "7", "0.128"]], "source": "rmm.74toRealtime.txt (rounded to 3 decimals)", "fetched": "2026-10-02"},
  "links": [
   {"level": "view", "label": T("NOAA CPC 的 MJO 页面（最新相位图）", "NOAA CPC MJO page (latest phase diagrams)", "Halaman MJO NOAA CPC (gambar rajah fasa terkini)"), "url": "https://www.cpc.ncep.noaa.gov/products/precip/CWlink/MJO/mjo.shtml"},
   {"level": "try", "label": T("BoM 的 RMM 文本文件", "BoM RMM text file", "Fail teks RMM BoM"), "url": "http://www.bom.gov.au/climate/mjo/graphics/rmm.74toRealtime.txt"},
   {"level": "pro", "label": T("BoM MJO 监测页", "BoM MJO monitoring page", "Halaman pemantauan MJO BoM"), "url": "https://www.bom.gov.au/climate/mjo/"}]},
]

quiz = [
 {"stage": 5, "chapter": "ch14", "q": T("厄尔尼诺时，太平洋的信风通常怎样？", "During El Niño, what usually happens to the Pacific trade winds?", "Semasa El Niño, apakah biasanya berlaku kepada angin pasat Pasifik?"),
  "options": [T("变弱，甚至改吹西风", "They weaken, or even turn westerly", "Melemah, malah bertukar menjadi angin barat"), T("变得特别强", "They become extra strong", "Menjadi sangat kuat"), T("完全不变", "No change", "Tiada perubahan"), T("改为南北方向", "They turn north–south", "Bertukar arah utara–selatan")],
  "answer": 0, "why": T("信风变弱，暖水就往东流到南美洲那边。", "With weaker trades the warm water flows east towards South America.", "Dengan angin pasat lemah, air panas mengalir ke timur ke arah Amerika Selatan.")},
 {"stage": 5, "chapter": "ch14", "q": T("RONI 是 +1.36 °C，代表什么？", "The RONI reads +1.36 °C. What does that indicate?", "RONI ialah +1.36 °C. Apakah maksudnya?"),
  "options": [T("厄尔尼诺的状态", "El Niño conditions", "Keadaan El Niño"), T("拉尼娜的状态", "La Niña conditions", "Keadaan La Niña"), T("中性", "Neutral", "Neutral"), T("马来西亚的气温", "Malaysia's temperature", "Suhu Malaysia")],
  "answer": 0, "why": T("超过 +0.5 °C 就是厄尔尼诺的状态；要连续 5 季才算一次厄尔尼诺。", "Above +0.5 °C means El Niño conditions; 5 seasons in a row make an episode.", "Melebihi +0.5 °C bermakna keadaan El Niño; 5 musim berturut-turut menjadikannya satu episod.")},
 {"stage": 5, "chapter": "ch14", "q": T("MJO 在哪两个相位时，雨带在马来西亚、印尼上空？", "In which two MJO phases is the wet band over Malaysia and Indonesia?", "Dalam dua fasa MJO manakah jalur basah berada di atas Malaysia dan Indonesia?"),
  "options": [T("第 4、5 相位", "Phases 4 and 5", "Fasa 4 dan 5"), T("第 1、2 相位", "Phases 1 and 2", "Fasa 1 dan 2"), T("第 7、8 相位", "Phases 7 and 8", "Fasa 7 dan 8"), T("每一个相位都一样", "Every phase alike", "Semua fasa sama")],
  "answer": 0, "why": T("第 2、3 在印度洋，4、5 在海洋性大陆，6、7 在西太平洋。", "2–3 are over the Indian Ocean, 4–5 the Maritime Continent, 6–7 the western Pacific.", "2–3 di atas Lautan Hindi, 4–5 Benua Maritim, 6–7 Pasifik barat.")},
]

write_chapter(chapter, terms, sources, quiz, datasets)
