/* Offline service worker.

   The whole app — shell, every chapter, maps, icons — is precached on
   install, so there is no half-offline state: either it installed or it
   did not, and the About page says which.

   CACHE and ASSETS are regenerated by tools/build-sw.mjs (CI runs it on
   every push). The cache name is a hash of every file, so any change to
   any file — index.html included — makes installed copies update. */

/* --- generated:begin --- */
const CACHE = 'meteo-c0ad345b6d';
const ASSETS = [
  './',
  'css/app.css',
  'data/ch05.json',
  'data/datasets.json',
  'data/index.json',
  'data/maps/seasia.json',
  'data/maps/world.json',
  'data/quiz.json',
  'data/releases.json',
  'data/series/kl-humidity-2025.json',
  'data/sources.json',
  'data/terms.json',
  'favicon.ico',
  'icons/apple-touch-icon-180.png',
  'icons/favicon-32.png',
  'icons/icon-192.png',
  'icons/icon-512.png',
  'icons/icon-maskable-192.png',
  'icons/icon-maskable-512.png',
  'icons/og-image-square.png',
  'icons/og-image.png',
  'icons/splash/1125x2436-dark.png',
  'icons/splash/1125x2436-light.png',
  'icons/splash/1170x2532-dark.png',
  'icons/splash/1170x2532-light.png',
  'icons/splash/1179x2556-dark.png',
  'icons/splash/1179x2556-light.png',
  'icons/splash/1242x2688-dark.png',
  'icons/splash/1242x2688-light.png',
  'icons/splash/1284x2778-dark.png',
  'icons/splash/1284x2778-light.png',
  'icons/splash/1290x2796-dark.png',
  'icons/splash/1290x2796-light.png',
  'icons/splash/1536x2048-dark.png',
  'icons/splash/1536x2048-light.png',
  'icons/splash/1668x2388-dark.png',
  'icons/splash/1668x2388-light.png',
  'icons/splash/2048x2732-dark.png',
  'icons/splash/2048x2732-light.png',
  'icons/splash/750x1334-dark.png',
  'icons/splash/750x1334-light.png',
  'icons/splash/828x1792-dark.png',
  'icons/splash/828x1792-light.png',
  'index.html',
  'js/app.js',
  'js/charts.js',
  'js/config.js',
  'js/content.js',
  'js/datasets.js',
  'js/i18n.js',
  'js/maps.js',
  'js/markup.js',
  'js/physics.js',
  'js/prefs.js',
  'js/projections.js',
  'js/qrcode.js',
  'js/releases.js',
  'js/share.js',
  'js/swpolicy.js',
  'js/terms.js',
  'js/updatelogic.js',
  'js/widgets/index.js',
  'js/widgets/kit.js',
  'js/widgets/w5.js',
  'manifest.webmanifest',
];
/* --- generated:end --- */

// Other apps live on the same github.io origin; only this app's caches are ours.
const PREFIX = 'meteo-';

function cacheStrategy(urlString, selfOrigin) {
  let u;
  try { u = new URL(urlString); } catch (e) { return 'never'; }
  return u.origin === selfOrigin ? 'precache' : 'never';
}

self.addEventListener('install', event => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    // Added one by one: a single 404 must not leave the app uninstalled.
    const results = await Promise.allSettled(ASSETS.map(url => cache.add(new Request(url, { cache: 'reload' }))));
    const failed = results.map((r, i) => (r.status === 'rejected' ? ASSETS[i] : null)).filter(Boolean);
    if (failed.length) console.warn('[sw] could not precache:', failed);
    await self.skipWaiting();
  })());
});

self.addEventListener('activate', event => {
  event.waitUntil((async () => {
    const names = await caches.keys();
    await Promise.all(names.filter(n => n.startsWith(PREFIX) && n !== CACHE).map(n => caches.delete(n)));
    await self.clients.claim();
  })());
});

self.addEventListener('fetch', event => {
  const { request } = event;
  if (request.method !== 'GET') return;
  if (cacheStrategy(request.url, self.location.origin) !== 'precache') return;
  const url = new URL(request.url);

  if (request.mode === 'navigate') {
    event.respondWith((async () => {
      const root = new URL('./', self.location);
      const isRoot = url.pathname === root.pathname || url.pathname === `${root.pathname}index.html`;
      if (isRoot) {
        const cached = await caches.match('index.html');
        if (cached) return cached;
      }
      try {
        // Real sub-pages that are not precached (tests/) come from the network.
        return await fetch(request);
      } catch (e) {
        // Offline at a nested path: the shell's relative css/ and js/ would
        // resolve against the wrong depth, so redirect to the scope root; the
        // browser carries the #route across.
        if (!isRoot) return Response.redirect(root.pathname + url.search, 302);
        const cached = await caches.match('index.html');
        return cached || new Response('Offline', { status: 503 });
      }
    })());
    return;
  }

  event.respondWith((async () => {
    const cached = await caches.match(request, { ignoreSearch: true });
    if (cached) return cached;
    try { return await fetch(request); } catch (e) { return new Response('', { status: 504 }); }
  })());
});
